### ISSUE TITLE
uiState is not updated properly after calling setUiState

### ISSUE THREAD

**Issue by jonadeline** [algolia/instantsearch#4546]
## 🐛 Bug description

After calling manually `setUiState` from my custom menu component, the uiState object is not reflecting the change in the onStateChange event listener in the middleware.

## 🔍 Bug reproduction

https://codesandbox.io/s/svelte-forked-13ymr

On the above sandbox click on an entry in the custom menu. Check the console output (or URL params) to see the value of uiState object which is not reflecting the latest `setUiState` call. Actually it's always reflecting the previous value set.

**Comment by jonadeline** [comment]
Probably a duplicate of #4421

**Comment by eunjae-lee** [comment]
Hello @jonadeline ,
Thanks for the report! Indeed yours seems similar to #4421 
Sorry for taking too long to get back to you. I will take a look at this as soon as possible and keep you updated.

**Comment by francoischalifour** [comment]
Hey @jonadeline! You can see [in that sandbox](https://codesandbox.io/s/github/algolia/doc-code-samples/blob/feat/autocomplete-query-suggestions/InstantSearch.js/query-suggestions?file=/src/app.js) that `setUiState` works with HierarchicalMenu.

**Steps**

1. Click on the input
2. Select the "in Computers & Tablets" item
3. Notice that the category is refined

![image](https://user-images.githubusercontent.com/6137112/97561178-060fce80-19e0-11eb-8f17-bd305f988cba.png)

I didn't dig into your code but here are a few things that you can look for:

- Is the correct attribute refined?
- Is the [UI state](https://www.algolia.com/doc/api-reference/widgets/ui-state/js/) updated with the right value? (It should be of the format `{ hierarchicalMenu: { attribute: ['lvl0', 'lvl1'] } }`
- Is your Svelte app re-rendering on this UI state change?

So I don't think this is related to ##4421.

**Comment by jonadeline** [comment]
Bonjour François,

- Yes the correct attribute is refined and the search results match what the user has selected. 
- The UI State format is alright but the value is not good when I console.log in the middleware. I get the previous value of the attribute. So the URL params are wrong and I'm not able to highlight the current category in my menu (as my code is based on the uistate value) 
- Yes,  I enabled the reactivity in my menu component whenever the uistate change in order to highlight the right category.

**Comment by jonadeline** [comment]
Hi @francoischalifour,

By any chance did you check my sandbox code ?
Im still struggling with this and didnt find any good workaround at the moment. 

Merci !

**Comment by dhayab** [comment]
Hi! We're doing a round of clean up in this repository. This issue seems not to have generated much activity lately. Is it still relevant?
