### ISSUE TITLE
`getServerState` doesn't correctly handle exceptions and crashes entire node server

### ISSUE THREAD

**Issue by sixers** [algolia/instantsearch#5233]
## 🐛 Bug description

`getServerState` doesn't correctly handle exceptions in search client (e.g. `ECONNREFUSED`), which causes it to hang forever, and crashes the entire node server if there's no defined handler for `'unhandledRejection'`.

## 🔍 Bug reproduction

**Live reproduction:**

This is the minimal Remix reproduction:

https://stackblitz.com/edit/node-vn7ere?file=app/entry.server.tsx

Steps to test:

1. Run the StackBlitz WebContainer - it should crash
2. Uncomment code in `app/entry.server.tsx`, which defines `process.on('unhandledRejection', ...)` handler and restart everything. Now the server should not crash, but `getServerState` will still hang forever
3. The workaround is to add `Promise.race`: see `index.tsx`

Note that this bug is not specific to Remix - I was able to reproduce it in Next as well.

## 💭 Expected behavior

`getServerState` should correctly propagate exceptions so that they can be catched. `unhandledRejection` handler should not be required.

## Environment

- React InstantSearch Hooks version: [6.38.1]
- React version: [e.g. 17.0.2]
- Browser: [N/A]
- OS: [Linux]
- Node version: v16.14.2 and v18.12.0

**Comment by Haroenv** [comment]
Hey @sixers, sorry for missing this error. I've just investigated and found the root source of the error not being caught by our mechanism. 

I've opened https://github.com/algolia/instantsearch/pull/5405 that will cover this, but for the time being you can indeed set global error handlers.
