### ISSUE TITLE
[react-instantsearch-hooks] RefinementList search state cleared on un-mount even when using useRefinementList to create a virtual widget

### ISSUE THREAD

**Issue by jamespeilow** [algolia/instantsearch#5240]
## 🐛 Bug description

When placing a `<RefinementList>` component inside a modal component that mounts and un-mounts its content, the current refinements are cleared even when using the `useRefinementsList` hook to create a virtual refinement list widget.  

## 🔍 Bug reproduction

Minimal example set up on Codesandbox, using the [Algolia docs example](https://www.algolia.com/doc/guides/building-search-ui/widgets/customize-an-existing-widget/react-hooks/#building-a-virtual-widget-with-hooks) as a reference.

**Steps to reproduce the behavior:**

1. Go to https://codesandbox.io/s/snowy-field-22wyku?file=/src/App.js
2. Click on the "Show DIalog" button to open the modal 
3. Apply a refinement (notice that the hits have updated)
4. Close the modal by clicking outside the modal body
5. The refinement has reset and all results show (refinement state has been cleared)

**Live reproduction:**

https://codesandbox.io/s/snowy-field-22wyku?file=/src/App.js

## 💭 Expected behavior

Current refinement search state should be preserved when the `<RefinementList>` component inside the modal component is unmounted on close. 

## Environment

- React InstantSearch Hooks version: 6.29.0
- React version: 18.0.0
- Browser: Chrome 103.0.5060.53
- OS: macOS

Thanks

**Comment by AntoineDuComptoirDesPharmacies** [comment]
In the past, we were able to avoid clean on unMount by deleting the `cleanUp` function of the custom connector.

Is there any way, in `react-instantsearch-hooks`, with custom connectors to avoid cleaning process ?

We tried to override the `dispose` method without success, the state is still reset.

**Comment by timhonders** [comment]
We have a similar issue with react-native an a Modal with refinements.

So i made a similar solution like @AntoineDuComptoirDesPharmacies for useRefinementList

```
import connectRefinementList from 'instantsearch.js/es/connectors/refinement-list/connectRefinementList.js';
import { useConnector } from 'react-instantsearch-hooks';

const useRefinementList = (props, additionalWidgetProperties) => {

    const overridenConnectRefinementList = (renderFn, unmountFn) => {
        const connector = connectRefinementList(renderFn, unmountFn);

        return (props) => {
            const newInstance = connector(props)
            newInstance.dispose = () => {
                unmountFn();
            };

            return newInstance;
        };
    }

    return useConnector(overridenConnectRefinementList, props, additionalWidgetProperties);
}

export default useRefinementList;
```

**Comment by Haroenv** [comment]
This should actually be fixed with the `future={{ preserveSharedStateOnUnmount: true }}` option on InstantSearch: https://www.algolia.com/doc/guides/building-search-ui/widgets/show-and-hide-widgets/react/#enable-preservesharedstateonunmount / https://www.algolia.com/doc/api-reference/widgets/instantsearch/react/#widget-param-preservesharedstateonunmount
