### ISSUE TITLE
WARNING - Detected multiple renderers concurrently rendering the same context provider (React 18.0.0?)

### ISSUE THREAD

**Issue by DB-Alex** [algolia/instantsearch#5243]
## 🐛 Bug description

I get the following warning on the server side in react when i use:

import { findResultsState } from 'react-instantsearch-dom/server';

Warning: Detected multiple renderers concurrently rendering the same context provider. This is currently unsupported.
    at Index (node_modules/react-instantsearch-core/dist/cjs/widgets/Index.js:86:34)
    at IndexWrapper (node_modules/react-instantsearch-core/dist/cjs/widgets/Index.js:157:31)

Modules in package.json:

"react": "^18.0.0",
"react-dom": "^18.0.0",
"algoliasearch": "^4.13.0",
"react-instantsearch-dom": "^6.23.3",

**Comment by Haroenv** [comment]
This issue has been closed in React, as it was unintentional. In the next release of react this warning will no longer show.

see: https://github.com/facebook/react/pull/22797#event-8210769332
