### ISSUE TITLE
RefinementList label customization

### ISSUE THREAD

**Issue by LeComptoirDesPharmacies** [algolia/instantsearch#5250]
**Is your feature request related to a problem? Please describe 🙏**

RefinementList component can not receive custom label like ToggleRefinement do. It always use raw 'attribute' as label.
Thus, it is more difficult to display a beautiful label in `CurrentRefinements` component/connector.

**Describe the solution you'd like 🤔**

Two possible solutions : 

1. Add a `label` prop to `connectCurrentRefinements` and `CurrentRefinements` and use it in `getMetadata` function.
2. Add a `translations` prop to `connectCurrentRefinements` and `CurrentRefinements` and use it to convert the attribute name to intelligible name.

**Describe alternatives you've considered ✨**

I am going to translate the label in my display component using attribute raw name (ex : owner.nickname) as source.

**Additional context**

No additional context.

**Comment by Haroenv** [comment]
In v7 there's a label in current refinements
