### ISSUE TITLE
Merge props given both in Configure and other widgets

### ISSUE THREAD

**Issue by zackify** [algolia/instantsearch#5265]
**Bug: What is the current behavior?**
Adding a facetFilter with Configure works. Apply a filter on a Refinement list, and it is removed.

**Bug: What is the expected behavior?**
To merge refinements and add facetFilters from configure

**Comment by Haroenv** [comment]
In the end this doesn't have a clear path and makes configure significantly harder. I recommend to see it as a "can be overridden by other widgets" state, and to use a parameter (like `filters`) which isn't used by another widget on the page.
