### ISSUE TITLE
RefinementList is getting checked after the results are refined. Bad UX for slow internet connections

### ISSUE THREAD

**Issue by harshmaur** [algolia/instantsearch#5268]
Hello, 

using **react-instantsearch** - latest

I tried to throttle my network and selected refinements, it seems like the checkbox gets selected after algolia is able to make the network call and fetch the results, this could lead to a bad UX as the user might think its not yet selected and click again which would make another API call. 

Wanted to know how we can go around this. 

Thanks!

**Comment by Haroenv** [comment]
This is solved in v7 (and earlier in hooks) through https://github.com/algolia/instantsearch/pull/5429
