### ISSUE TITLE
infinite loop when rendering a conditional loading message with children

### ISSUE THREAD

**Issue by blech75** [algolia/instantsearch#5269]
**Do you want to request a *feature* or report a *bug*?**

Bug.

**Bug: What is the current behavior?**

(See below for full description.)

Attempting to use a connected "loading message" component (one that renders static content when loading and its children when finished) causes an infinite loop in certain circumstances.

* when `children` contains the `<Stats />` component, `searchResults.searching` is set as expected.
* when `children` contains the `<Hits />` and `<Pagination />` components (possibly others), `searchResults.searching` flips back and forth ad infinitum.

When the "loading message" component is configured to render static content upon completion, the infinite loop does not occur.

**Bug: What is the expected behavior?**

`searchResults.searching` should not flip-flop between `true` and `false` in an infinite loop when rendering `children`.

**Bug: What browsers are impacted? Which versions?**

Observed in Chrome 59.0.3071.109 & Safari 10.1.1.

**What is the version you are using? Always use the latest one before opening a bug issue.**

Observed in react-instantsearch 4.0.3 and 4.0.4.
 
----

### Background

(copied/adapted from [discussion on community forum](https://discourse.algolia.com/t/searching-multiple-indices-with-different-fields-loading-indicator/1647/8).)

Using the example connector provided [in your docs](https://community.algolia.com/react-instantsearch/guide/Conditional_display.html#displaying-content-when-loading):
```
const connectLoading = createConnector({
  displayName: 'ConditionalError',
  getProvidedProps(props, searchState, searchResults) {
    return {
      loading: searchResults.searching
    };
  }
});
```

I then create a component that renders a message when loading, and its children when complete:
```
const LoadingMessage = connectLoading(({ loading, children }) =>
  <div>
    {loading ? <p>Loading...</p> : children }
  </div>
);
```

Now we make use of it in a minimal UI where we just display the stats:
```
<InstantSearch ...>
  <SearchBox />

  <div className="SearchResults">
    <LoadingMessage>
      <p>FINISHED!</p>
      <Stats />
    </LoadingMessage>
  </div>

</InstantSearch>
```

You can see this example here in a codepen: [`https://codepen.io/wrksprfct/full/jwmmox/`](https://codepen.io/wrksprfct/full/jwmmox/). This works as expected. Load the page and you see "Loading..." and then "FINISHED! X results found in Yms". Ensure you have web console open and you'll see the XHRs fly by and `searchResults.searching` toggle between `true` and `false` when things change state. Type "avocado" into the box: the UI updates and the console logs as you'd expect.

Now here's the fun part. Let's replace the `<Stats />` component with the `<Hits />` component, so it looks like this:
```
<InstantSearch ...>
  <SearchBox />

  <div className="SearchResults">
    <LoadingMessage>
      <p>FINISHED!</p>
      <Hits />
    </LoadingMessage>
  </div>
</InstantSearch>
```

You can see this example in another codepen: [`https://codepen.io/wrksprfct/full/yXbXNQ`](https://codepen.io/wrksprfct/full/yXbXNQ). **!!!BEWARE!!!** before loading that page, be prepared to kill it via Chrome's Task Manager or your OS's equivalent because it gets into an infinite loop and consumes CPU & gobs of memory quickly. Again, ensure you have the web console open.

So, upon loading that page, you'll see two XHRs instead of one (identical, AFAICT), and then `searchResults.searching` flip between `false` and `true` ad infinitum.

If, in this problematic example, you hardcode the `loading` prop to `false`:
```
getProvidedProps(props, searchState, searchResults) {
  return {
    loading: false
  };
}
```
...everything works. Well, except for seeing the loading message... which is the whole point of this exercise!

Again, the only difference is the switch from `<Stats />` to `<Hits />`.  I looked at their sources, but could not find anything interesting.

Interestingly, the same problematic behavior occurs with `<Pagination />`. See [`https://codepen.io/wrksprfct/full/zzzOWm/`](https://codepen.io/wrksprfct/full/zzzOWm/). I did not test any others yet.

Now... if we update the `LoadingMessage` component to not render children:
```
const LoadingMessage = connectLoading(({ loading }) =>
  <div>
    {loading ? <p>Loading...</p> : <p>DONE!</p> }
  </div>
);
```

... then everything works fine:
```
<InstantSearch ...>
  <SearchBox />

  <div className="SearchResults">
    <LoadingMessage />
  </div>
</InstantSearch>
```
You can see this example in action in this codepen: [`https://codepen.io/wrksprfct/full/WOOajx`](https://codepen.io/wrksprfct/full/WOOajx).

**Comment by mverissimo** [comment]
The same behavior happens with **v7** too, the following code `freezes` the page.

```jsx
function LoadingIndicator(props) {
  const { children } = props;
  const { status } = useInstantSearch();

  if (status === 'loading' || status === 'stalled') {
    return <p>Loading search results</p>;
  }

  return <div>{children}</div>;
}
```

**Comment by dhayab** [comment]
Hi @mverissimo, do you wrap InstantSearch widgets with `<LoadingIndicator>`? If so, you're mounting/unmounting these in an infinite loop. See [Show and hide widgets](https://www.algolia.com/doc/guides/building-search-ui/widgets/show-and-hide-widgets/react/) in our documentation for more info on how to handle mounting/unmounting widgets, for example by setting the `preserveSharedStateOnUnmount` flag in the latest version of React InstantSearch.

If your issue persists, don't hesitate to provide a reproducible sandbox.

**Comment by mverissimo** [comment]
Hi @dhayab, thanks for the fast feedback, I'm doing something like:
https://codesandbox.io/p/sandbox/exciting-jackson-mz44k3?file=%2Fcomponents%2FLayout.tsx%3A5%2C30

If I can't wrap a global loading around the app, what's the best way to show, thinking I need the status to check the `loading`.

**Comment by dhayab** [comment]
With the number of widgets you're wrapping, it might be more practical to keep them mounted but only switch their visibility with CSS (you'll need an actual HTML element to contain all the children though), something like:

```tsx
import React from "react";
import { useInstantSearch } from "react-instantsearch";

export function Layout(props) {
  const { children } = props;
  const { status, results } = useInstantSearch();

  const isFetching = status === "loading" || status === "stalled";

  return (
    <React.Fragment>
      <h1 style={{ display: isFetching ? 'block' : 'none' }}>loading</h1>
      <div style={{ display: isFetching ? 'none' : 'block' }}>{children}</div>
    </React.Fragment>
  );
}
```

**Comment by Haroenv** [comment]
This is also described in the "conditional display" guide, so I think the issue can be closed: https://www.algolia.com/doc/guides/building-search-ui/going-further/conditional-display/react/#handling-no-results
