### ISSUE TITLE
Multiple indexes on Nuxt SSR fails to hydrate fully

### ISSUE THREAD

**Issue by Gef** [algolia/instantsearch#5383]
**Bug 🐞**

### What is the current behavior?

On first load the server results come through fine, but when adding refinements from a shared refinement input, the results fail to update. You can see the requests going off to Algolia API, but only the initial 'parent' index receives the refinement input.

### Make a sandbox with the current behavior

https://codesandbox.io/s/vue-instantsearch-nuxt-multi-index-8qdvky?file=/pages/search.vue

This sandbox has been created using the multi-index documentation from Algolia as closely as possible, just using the SSR component rather than the ais-instant-search component. 
https://www.algolia.com/doc/guides/building-search-ui/ui-and-ux-patterns/multi-index-search/vue/

### What is the expected behavior?

The results should update as you refine

### Does this happen only in specific situations?

Just on first load, changing routes fixes the issue clientside

### What is the proposed solution?

I can't figure this one out

### What is the version you are using?

4.6.0

**Comment by dhayab** [comment]
Hi @Gef, thanks again for reporting this issue!

You can now update to vue-instantsearch@4.7.1, which includes a fix for it.
