### ISSUE TITLE
Refinement Lists not persisting when affected by a Vue Transition.

### ISSUE THREAD

**Issue by AdrianwithaW** [algolia/instantsearch#5393]
**Bug 🐞**

### What is the current behavior?
I'm using a set of refinements that I'd like to show/hide with a Vue `<transition>`. Have tried either basic transition setup as per the Vue docs. When the elements are transitioned in (what seems to be) any way at all, the refinements are all cleared 

### Make a sandbox with the current behavior
[Link to sandbox example](https://codesandbox.io/s/nifty-shadow-tvq4f), enable a refinement then click the "Toggle Refinements" under the search bar. Note the list transitions to the left and the search results change. Toggling the list again reveals it and you can see the refinement/s have been cleared/reset.

### What is the expected behavior?
Refinements should remain active, the DOM elements don't appear to be being re-rendered but the `state` attribute in the Vue components is quickly flicking from `null` back to it's loaded state which seems to be clearing the refinements.

### Does this happen only in specific situations?
Seems to happen with any type of transition at all.

### What is the proposed solution?
To retain the state of any refinements that are subject to a transition

### What is the version you are using?
Latest, as per sandbox.

Happy to provide any further details if necessary.

**Comment by s1mpLyy** [comment]
I fixed it using KeepAlive for the modal and for the dynamic component and replace the v-if with v-show

**Comment by Haroenv** [comment]
If you use the latest version of Vue InstantSearch, you can fix this by:

1. use `<ais-instantsearch :future="{ preserveSharedStateOnUnmount: true }">`
2. add a static (can be non-rendering, hidden) widget of the type that is conditionally rendered

I'll close this issue now, but the guide on https://www.algolia.com/doc/guides/building-search-ui/widgets/show-and-hide-widgets/react/ should be recreated for Vue (it behaves the same)

**Comment by s1mpLyy** [comment]
> If you use the latest version of Vue InstantSearch, you can fix this by:
> 
> 1. use `<ais-instantsearch :future="{ preserveSharedStateOnUnmount: true }">`
> 2. add a static (can be non-rendering, hidden) widget of the type that is conditionally rendered
> 
> I'll close this issue now, but the guide on https://www.algolia.com/doc/guides/building-search-ui/widgets/show-and-hide-widgets/react/ should be recreated for Vue (it behaves the same)

idk why this is not working for me btw i'm using nuxt/@algolia last version

**Comment by Haroenv** [comment]
Are you using the latest Vue InstantSearch version though? maybe nuxt/algolia hasn't been updated yet?
