### ISSUE TITLE
Missing vue-server-renderer/basic module on build

### ISSUE THREAD

**Issue by Jaimeloeuf** [algolia/instantsearch#5394]
**Bug 🐞**

### What is the current behavior?
Currently after building my app, the vue cli shows the following error:
```
warning  in ./node_modules/vue-instantsearch/dist/vue-instantsearch.esm.js

Module not found: Error: Can't resolve 'vue-server-renderer/basic' in 'C:\code\classpass\app\node_modules\vue-instantsearch\dist'
```

### Does this happen only in specific situations? And What is the version you are using?
This only happened right after I upgraded dependencies for algolia related items:
- algoliasearch
    - from 4.2.0 to 4.3.0
- vue-instantsearch
    - from 2.7.0 to 3.1.0

**Comment by Haroenv** [comment]
Thanks, there indeed haven't really been any reports of this in a while, I assume bundlers have caught up? Let's close for now.
