### ISSUE TITLE
HitsPerPage doesn’t work correctly with routeToState()

### ISSUE THREAD

**Issue by joshangell** [algolia/instantsearch#5397]
**Bug 🐞**

### What is the current behavior?

- Use the `ais-hits-per-page` component as described in the docs
- Then set up the routing as per the "User-friendly URLs" section detailed here: https://www.algolia.com/doc/guides/building-search-ui/going-further/routing-urls/js/#user-friendly-urls
- Using the widget updates the UI state correctly and also updates the URL
- Reloading the page sets the state correctly but doesn’t update the UI of the widget

### Make a sandbox with the current behavior

Sandbox example: https://codesandbox.io/embed/vueinstantsearchv2starter-8jx9i

### What is the expected behavior?

The dropdown should reflect the selected option in the URL when you have selected something other than the default and then reloaded the page.

### What is the proposed solution?

Unsure!

### What is the version you are using?

v2.1.0

**Comment by jonathan-bird** [comment]
This would still be amazing to have @Haroenv if it's on the cards.

**Comment by Haroenv** [comment]
This makes sense, I've just opened a PR which fixes it so you won't need that workaround anymore in the future.

**Comment by jonathan-bird** [comment]
Too good, thanks!
