### ISSUE TITLE
Broken Link found in `instantsearch.js` documentation

### ISSUE THREAD

**Issue by pruthvi145** [algolia/instantsearch#5414]
### 🐛 Current behavior

I found a broken link for changelog in [instantsearch.js](https://www.algolia.com/doc/guides/building-search-ui/what-is-instantsearch/js/#stay-up-to-date) documentation

I know this is a very small change to be done and I would like to do the change myself but I could not find any way to contributing in the documentation. Am I missing something?🤔

PS: There should a separate template for documentation related issues
### 🔍 Steps to reproduce

1. Go to [Stay up to date](https://www.algolia.com/doc/guides/building-search-ui/what-is-instantsearch/js/#stay-up-to-date) section of '[What is InstantSearch.js?](https://www.algolia.com/doc/guides/building-search-ui/what-is-instantsearch/js/)' page in the documentation
2. Click on "changelog" link

### 💭 Expected behavior

Redirect to [this](https://github.com/algolia/instantsearch/blob/master/packages/instantsearch.js/CHANGELOG.md) page

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Haroenv** [comment]
The right link is https://github.com/algolia/instantsearch/blob/master/packages/instantsearch.js/CHANGELOG.md, I'm updating the docs. Thanks!
