### ISSUE TITLE
Bug: incorrect highlight with full-width characters

### ISSUE THREAD

**Issue by shigma** [algolia/instantsearch#5444]
### 🐛 Current behavior

<img width="627" alt="image" src="https://user-images.githubusercontent.com/33423008/214236217-a570359d-6d5a-45f7-9b6e-9b73c0724a84.png">

I searched with the 2-character word "测试", but got 5 characters highlighted.

### 🔍 Steps to reproduce

1. go to the page below
2. search "测试"
3. see the incorrect highlight

### Live reproduction

https://koishi.chat

### 💭 Expected behavior

Only "测试" should be hightlighted.

### Package version

vue-instantsearch 4.7.2

### Operating system

not relavent

### Browser

not relavent

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Haroenv** [comment]
You've marked this issue as closed, did you find out what was causing it? I believe it would be the actual engine returning those highlights, if they happen consistently. Possibly synonyms are also involved?

**Comment by shigma** [comment]
Yes. It seems an issue from meilisearch. Their `matchesInfo` contains byte length instead of character length. So I'll be tracking this issue on their side.
