### ISSUE TITLE
Vue-instantsearch Vue 3: Refreshing cache not updating UI

### ISSUE THREAD

**Issue by ValdoGhafoor** [algolia/instantsearch#5514]
### 🐛 Current behavior

Hi,

I want to refresh my ais-infinite-hits items when a user action (edit a document) is performed.

I follow this guide to do so: https://www.algolia.com/doc/guides/building-search-ui/going-further/improve-performance/vue/#caching

First of all, the Vue 3 example is using deprecated mixins & destroyed which should be updated to the proper way to do it

Then, using the periodic & manual cache refresh, I can see my updated document being fetched in my chrome network tab.

However, the AisInfiniteHits items are not updated accordingly.

I created a reproduction, however I don't know any public Algolia Index (is there one ?) so you have to edit the repro to specify it.
If you have suggestions on how to make the repro work for everyone without having to fill your own index, feel free to tell me and I will update it.

### 🔍 Steps to reproduce

1. Add VueInstantSearch
2. Use AisInfiniteHits
3. Create an AisRefresh component as stated by the guide (both manual & periodic have the issue)
4. Edit a document in the Algolia Console or using a remote server request
5. Manually refresh or wait for the periodic refresh
6. Watch your network tab to be sure the updated item is being fetched and not the old one
7. Watch the item you edited not being updated in the UI

### Live reproduction

https://codesandbox.io/s/hungry-black-xj6llh?file=/src/components/AisRefresh.vue

### 💭 Expected behavior

Refreshing cache using the guide code should also update the UI

### Package version

vue-instantsearch 4.8.4, algoliasearch 4.14.3, vue 3.2.45

### Operating system

macos 13.2

### Browser

Firefox 110 & chrome 110

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by aymeric-giraudet** [comment]
Hi @ValdoGhafoor,

The cache for `ais-infinite-hits` is separate and we do not provide a way to invalidate it.

However there is a `cache` prop so you can provide your own, you can make a custom cache that can be invalidated like I made here : https://codesandbox.io/s/twilight-voice-d5zuj6?file=/src/App.vue (I wanted to import `isEqual` from `instantsearch.js` but it doesn't seem to work so I copy/pasted it :/ )

You can then call `cache.invalidate` inside `refresh` or whenever you want to.

**Comment by ValdoGhafoor** [comment]
I see, thanks for the tip
