### ISSUE TITLE
Dropdown refinementlist crashes on search

### ISSUE THREAD

**Issue by stephanemartinw** [algolia/instantsearch#5543]
### 🐛 Current behavior

When searching  in a dropdown refinementlist, code crashes into following error: 

<img width="540" alt="Capture d’écran 2023-03-14 à 12 21 48" src="https://user-images.githubusercontent.com/8926622/224986254-aeae8edd-6cc5-4acc-ac31-ef9611815f8a.png">

### 🔍 Steps to reproduce

Go to the attached codesandbox url, start a search with 'test' in the searchbox.
Then click on the filter button and inside the dropdown, search for a value: 'bio'

### Live reproduction

https://codesandbox.io/s/keen-lake-pp46dw

### 💭 Expected behavior

No error

### Package version

latest instantsearch.js 4.52.0 and algoliasearch 4.15.0

### Operating system

macOS

### Browser

Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Haroenv** [comment]
Not sure why the error is not properly shown (possibly https://github.com/algolia/algoliasearch-client-javascript/issues/1444), but this is because you're attribute isn't set up for searching in the index configuration:

```json
{
    "message": "Cannot search in `culinary_categories` attribute, you need to add `searchable(culinary_categories)` to attributesForFaceting.",
    "status": 400
}
```
