### ISSUE TITLE
Showcase for React InstantSearch Hooks widgets is glitchy

### ISSUE THREAD

**Issue by gregsadetsky** [algolia/instantsearch#5565]
### 🐛 Current behavior

While trying the React InstantSearch Hooks widgets showcase located [here](https://www.algolia.com/doc/guides/building-search-ui/widgets/showcase/react-hooks/), I noticed that typing relatively fast in the searchBox leads to some letters "glitching" and not being added to the search box. i.e. if I type "screen laptop", the search box ends up "eating" some of the letters, and the input has "scren laptp" at the end.

See demonstration video below. In it, I am trying to type "screen laptop", followed by "nintendo" and then "biometric"

https://user-images.githubusercontent.com/1017304/227829091-332c17ea-a3f9-47c4-a172-7de81799cc80.mov

### 🔍 Steps to reproduce

1. go to https://www.algolia.com/doc/guides/building-search-ui/widgets/showcase/react-hooks/
2. type a search query relatively fast
3. the query will be missing some letters

### Live reproduction

n/a

### 💭 Expected behavior

The search input should not "lose" any letters

### Package version

n/a

### Operating system

macOS 12.4

### Browser

Chrome Version 111.0.5563.110 (Official Build) (arm64)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Haroenv** [comment]
This actually only happens in the showcase as it's using an older version of Vue InstantSearch that didn't yet fix the issue, which has happened in https://github.com/algolia/vue-instantsearch/pull/1133 

Is this something you see outside of the showcase?

**Comment by gregsadetsky** [comment]
I haven't seen it outside of the showcase, no. Thanks -- that does seem to be the issue here
