### ISSUE TITLE
InstantSearchSSRProvider makes nested InstantSearch queries global

### ISSUE THREAD

**Issue by fmedinac** [algolia/instantsearch#5585]
### 🐛 Current behavior

We have multiple nested `<InstantSearch />` to handle scenarios like carousels with specific filters and a typeahead function displaying hits before search query submission.

We use `<Configure />` (`useConfigure` in some cases) to handle these cases.

When we implemented `<InstantSearchSSRProvider />`, things started to get strange. For example, when users start inputing a search query, the route changes and apply the query with the global `<InstantSearch />`, even though its closest `<InstantSearch />` has no routing defined.

In the sandbox attached it's possible to see that ssr.tsx only differs on having `<InstantSearchSSRProvider />` wrapping the app.

### 🔍 Steps to reproduce

1. In the Sandbox, search for "Nike" on the left panel and "Adidas" on the right
2. Confirm both columns are displaying independent hits
3. Open the SSR variation and repeat the same process
4. Notice that now both input fields are in sync, while they should not

### Live reproduction

https://codesandbox.io/s/delicate-cache-y2dj5v

### 💭 Expected behavior

Nested `<InstantSearch />` should set its children's components/hooks behaviors.

### Package version

"react-instantsearch-hooks-router-nextjs": "6.42.1",     "react-instantsearch-hooks-server": "6.42.1",     "react-instantsearch-hooks-web": "6.42.1"

### Operating system

macOS 12.6

### Browser

Brave 1.50.114

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by fmedinac** [comment]
In the code sandbox (need to test on actual app), I was able to make it work by adding an `<InstantSearchSSRProvider  initialResults={{}} />` (`initialResults` required) wrapping the nested `<InstantSearch />`, is that expected?

I mean, Is it required to have an `InstantSearchSSRProvider` wrapping every `InstantSearch` even though I only care about hydrating the one at the top level?

**Comment by Haroenv** [comment]
Before looking more in detail, I'd like to already say that InstantSearchSSRProvider is designed for one having a single InstantSearch component as its child. We should have a warning (or maybe even error) if there are multiple, as they will share the states.

The pattern you may be looking for could be "multiple root indices":

```jsx
const searchClient = algoliasearch();
searchFn = searchClient.search;
searchClient.search = (queries) => {
  queries.shift();
  return searchFn(queries).then(({ results }) => ({
    results: [
      {
        hits: [],
        nbHits: 0,
        nbPages: 0,
        page: 0,
        processingTimeMS: 0,
        hitsPerPage: 0,
        exhaustiveNbHits: false,
        query: '',
        params: '',
      },
      ...results,
    ],
  }));
};

function App() {
  return (
    <InstantSearch indexName="_root_index_" searchClient={searchClient}>
      <Index indexName="1" />
      <Index indexName="2" />
    </InstantSearch>
  );
}
```

Index 1 and index 2 will not share any state in this setup.
