### ISSUE TITLE
Catch all routes with "react-instantsearch-hooks-router-nextjs" do not work

### ISSUE THREAD

**Issue by DB-Alex** [algolia/instantsearch#5586]
### 🐛 Current behavior

Catch all routes with "react-instantsearch-hooks-router-nextjs" do not work. The browser button does not work at all.

@aymeric-giraudet I tried solving it with your beforePopState solution. But this does not even get triggered. 

### 🔍 Steps to reproduce

Create a [...all].js in pages.js

Then make the instant search pages use the same catch all route as the hit.

The fix is in https://github.com/algolia/instantsearch/blob/master/packages/instantsearch.js/src/lib/routers/history.ts =>

Problem is

`  public dispose(): void {
    if (this._dispose) {
      this._dispose();
    }

    this.isDisposed = true;

    safelyRunOnBrowser(({ window }) => {
      if (this._onPopState) {
        window.removeEventListener('popstate', this._onPopState);
      }
    });

    if (this.writeTimer) {
      clearTimeout(this.writeTimer);
    }

    this.write({} as TRouteState);
  }`

This last rule should not be there for next to work.

`
    this.write({} as TRouteState);
`
When I comment this line everything works as expected.

### Live reproduction

https://codesandbox.io/s/github/algolia/instantsearch.js/tree/templates/react-instantsearch

### 💭 Expected behavior

Catch all routes with getStaticProps should work.

### Package version

next 13.3.0, react-instantsearch-hooks-router-nextjs 6.42.1, react-instantsearch-hooks-server 6.42.1, react-instantsearch-hooks-web 6.42.1

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by DB-Alex** [comment]
Hi @aymeric-giraudet the product pages in my case dont have InstantSearch at all. But they are on the same catch all next route.

**Comment by aymeric-giraudet** [comment]
Hi @DB-Alex,

Do you mean you have a condition in which based on the slug caught in `[...all].js`, you conditionally render either a Hit page or an `InstantSearch` page ? Then it would make sense than dispose is called indeed.

However would it be possible to still declare an actual route for InstantSearch ? Like having a `search.js` page for it then the rest can be caught in `[...all].js` for hits, maybe that would fix things ?

Once again it's a bit difficult to tell without a reproduction, providing one would help us greatly for fixing this :)

**Comment by DB-Alex** [comment]
Hi @aymeric-giraudet,

Thats indeed the case, we have very dynamic routes based on our CMS system.

So a route can be category page but also a product page.

We have a [...all].js then in getStaticProps we check what kind of page we need to load and the render method is like this:

```
{(pageType === 'product') ? (
    <ProductPage
        {...props}
    />
) : (
    <ConditionalWrapper
        condition={(!isEmpty(index))}
        wrapper={(children) => (
            <InstantSearchSSRProvider
                {...serverState}
                key={getProviderKey({ path: router.asPath })}
            >
                <InstantSearch
                    {...index}
                    serverStateProps={serverStateProps}
                >
                    {children}
                </InstantSearch>
            </InstantSearchSSRProvider>
        )}
    >
        <BlocksPage
            {...props}
        />
    </ConditionalWrapper>
)}
```

So we are navigating to a product and the instant search index is gone. But we are still on the same route for nextjs.

Hope this clears the issue for you.

**Comment by DB-Alex** [comment]
Great! Yeah i am aware of the separated pages but this client wants extreme flexibility. I simple do not know what the url will be or what kind of page will be on it.

Here is my router implemention:

```
// @todo
// To use algolia-next.js this bug should be resolved first
// https://github.com/algolia/instantsearch/issues/5586

let {
	indexParams,
	filterDivider,
	segmentOrder,
} = CategoryConfig;

export const router = ({
	filters,
	indexName,
	serverStateProps = {},
}) => {
	let { path } = serverStateProps;

	indexName = getIndexName({ indexName });

	return {
		router: createInstantSearchRouterNext({
			routerOptions: {
				createURL: ({
					routeState,
					location,
				}) => {
					let url = getCleanPath({ path: location.pathname });
					let indexParamsValues = Object.values(indexParams);
					let filterUrl = filterDivider;

					for (let indexParamsKey of segmentOrder) {
						if (routeState[indexParams[indexParamsKey]]) {
							url += `${indexParams[indexParamsKey]}-${routeState[indexParams[indexParamsKey]]}/`;
						}
					}

					Object.keys(routeState).forEach((key) => {
						let value = routeState[key];

						if (value) {
							if (Array.isArray(value)) {
								value = map(value, (o) => encodeURIComponent(o));
							} else {
								value = encodeURIComponent(value);
							}

							if (!indexParamsValues.includes(key)) {
								filterUrl += `/${encodeURIComponent(key)}:${value.join(',')}`;
							}
						}
					});

					if (filterUrl !== filterDivider) {
						url += `${filterUrl}/`;
					}

					return url;
				},
				parseURL: ({
					location,
				}) => {
					let url = new URL(location);
					let routeState = {};

					for (let indexParamValue of Object.values(indexParams)) {
						let regex = new RegExp(`/${indexParamValue}-[^/]*`, 'g');
						let findIndexParam = regex.exec(url.pathname);

						if (Array.isArray(findIndexParam) && findIndexParam.length > 0) {
							routeState[indexParamValue] = findIndexParam[0].replace(`/${indexParamValue}-`, '');
						}
					}

					if (url.pathname.indexOf(filterDivider) !== -1) {
						let segments = url.pathname.split('/');
						let filterIndex = segments.indexOf('filter');
						let filters = [];

						segments.forEach((segment, index) => {
							if (segment && segment !== 'filter') {
								if (filterIndex !== -1 && index > filterIndex) {
									filters.push(segment);
								}
							}
						});

						if (!isEmpty(filters)) {
							filters.forEach((filter) => {
								if (filter) {
									let [key, value] = filter.split(':');

									if (value) {
										value = value.split(',');

										if (Array.isArray(value)) {
											value = map(value, (o) => decodeURIComponent(o));
										}

										routeState[key] = value;
									}
								}
							});
						}
					}

					return routeState;
				},
			},
			serverUrl: (path) ? `${process.env.NEXT_PUBLIC_BASE_URL}${path}` : process.env.NEXT_PUBLIC_BASE_URL,
			singletonRouter,
		}),
		stateMapping: {
			stateToRoute(uiState) {
				let routeState = {};
				let indexUiState = uiState[indexName];

				if (indexUiState) {
					routeState = {
						pagina: indexUiState.page,
						query: indexUiState.query,
						sorteren: getSortByValue({
							indexName,
							value: indexUiState.sortBy,
						}),
					};

					if (Array.isArray(filters)) {
						filters.forEach(({
							attribute,
							label,
						}) => {
							let urlKey = slugify(label);

							if (indexUiState?.refinementList?.[attribute]) {
								routeState[urlKey] = indexUiState.refinementList[attribute];
							}
						});
					}

					routeState = omitBy(routeState, isNil);
				}

				return routeState;
			},
			routeToState(routeState) {
				let uiState = routeState;

				if (indexName) {
					let indexUiState = {
						page: (routeState.pagina) ? parseInt(routeState.pagina) : undefined,
						query: routeState.query,
						sortBy: getSortByValue({
							indexName,
							routeState: true,
							value: routeState.sorteren,
						}),
						refinementList: {},
					};

					if (Array.isArray(filters)) {
						filters.forEach(({
							attribute,
							label,
						}) => {
							let urlKey = slugify(label);

							if (routeState?.[urlKey]) {
								indexUiState.refinementList[attribute] = routeState[urlKey];
							}
						});
					}

					indexUiState = omitBy(indexUiState, isNil);
					indexUiState.refinementList = omitBy(indexUiState.refinementList, isNil);

					if (isEmpty(indexUiState.refinementList)) {
						delete indexUiState.refinementList;
					}

					uiState = {
						[indexName]: indexUiState,
					};
				}

				return uiState;
			},
		},
	};
};
```

CategoryConfig:

```
export default {
	filterDivider: 'filter',
	indexParams: {
		page: 'pagina',
		query: 'query',
		sortBy: 'sorteren',
	},
	segmentOrder: ['sortBy', 'query', 'page'],
};
```

Please let me know if I can help.

**Comment by aymeric-giraudet** [comment]
Thanks @DB-Alex !

I think this is because this `createURL` implem does not take `location.protocol` and `location.host` into account.

To debug you could add this to `node_modules/instantsearch.js/es/lib/routers/history.js` at line 257 (inside `shouldWrite` basically) : 
```js
console.log(url, window.location.href);
```

And change your `createURL` implem so that the two strings are the same when you go on a hit page. I suspect for now it will be something like `/product-xxx` and `http://localhost/product-xxx` which is why it writes when it shouldn't.

Hope that helps !

**Comment by DB-Alex** [comment]
Hi @aymeric-giraudet,

That was indeed the case! Thanks for your help :D

**Comment by DB-Alex** [comment]
I think I was to early. Now the URLS are exactly the same but I get this warning:

```
The UI state for the index "v3_products" is not consistent with the widgets mounted.
is can happen when the UI state is specified via `initialUiState`, `routing` or `setUiState` but that the widgets responsible for this state were not added. This results in those query parameters not being sent to the API.
```

Of course all the virtual widgets are there...

**Comment by DB-Alex** [comment]
Nevermind component was not unmounting, everything works as expected!
