### ISSUE TITLE
useRefinementList: eslint fails with error "Avoid referencing unbound methods which may cause unintentional scoping of this"

### ISSUE THREAD

**Issue by VitaliyPotapov** [algolia/instantsearch#5589]
### 🐛 Current behavior

When using `useRefinementList` as per [documentation](https://www.algolia.com/doc/api-reference/widgets/refinement-list/react-hooks/#hook) there is `@typescript-eslint` error:
```
Avoid referencing unbound methods which may cause unintentional scoping of `this`
```

### 🔍 Steps to reproduce

1. enable [@typescript-eslint/recommended-requiring-type-checking](https://typescript-eslint.io/linting/configs#recommended-requiring-type-checking) in the project
2. use the following code:
    ```ts
   const { refine } = useRefinementList({ attribute: 'brand' });
    ```
3. run eslint and see output:
    ```
    Error: Avoid referencing unbound methods which may cause unintentional scoping of `this`.
    If your function does not access `this`, you can annotate it with `this: void`, or consider using an arrow function instead.  @typescript-eslint/unbound-method
    ```

### Live reproduction

https://codesandbox.io/embed/heuristic-chihiro-f2nv7x?fontsize=14&hidenavigation=1&theme=dark

### 💭 Expected behavior

Eslint check pass

### Package version

algoliasearch 4.16.0 react-instantsearch-hooks-web 6.42.0

### Operating system

macOS 13.1

### Browser

Chrome/112.0.0.0

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Haroenv** [comment]
The sandbox you shared doesn't have eslint configured, and is also not using useRefinementList as far as I can tell.

Could you share this somewhere it actually reproduces please? Thanks!

Our methods can safely be restructured, so I'm guessing this is somehow a false positive, although I'm not suer what we'd need to change to avoid typescript-eslint thinking the method loses its binding.

**Comment by VitaliyPotapov** [comment]
@Haroenv I've updated sandbox to demonstrate an issue: https://codesandbox.io/p/sandbox/heuristic-chihiro-f2nv7x?file=%2Fpackage.json&selection=%5B%7B%22endColumn%22%3A25%2C%22endLineNumber%22%3A6%2C%22startColumn%22%3A25%2C%22startLineNumber%22%3A6%7D%5D

After running in terminal `npm run lint` I get the following error:

<img width="1476" alt="image" src="https://user-images.githubusercontent.com/121876357/231492461-741b4654-e626-4b8b-be6b-7f2cd1bad90e.png">
