### ISSUE TITLE
DevTools failed to load source map:

### ISSUE THREAD

**Issue by Rurouni-z** [algolia/instantsearch#5637]
### 🐛 Current behavior

DevTools failed to load source map: Could not load content for https://cdn.jsdelivr.net/dist/instantsearch.min.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE

### 🔍 Steps to reproduce

see [my blog](https://www.keepjolly.com)

### Live reproduction

nothing

### 💭 Expected behavior

disapper waring

### Package version

https://cdn.jsdelivr.net/npm/instantsearch.js@2/dist/instantsearch.min.js

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Haroenv** [comment]
I believe this is not fixable due to #4416 and the jsDelivr underlying issue where the short links don't get redirected.

Possibly a solution like #3011  could be tried though, but I don't think it's robust enough, as source map URLs are not relative

**Comment by Rurouni-z** [comment]
> I believe this is not fixable due to #4416 and the jsDelivr underlying issue where the short links don't get redirected.
> 
> Possibly a solution like #3011 could be tried though, but I don't think it's robust enough, as source map URLs are not relative

ok thanku, i found it just use to debug, so i will let it be.
