### ISSUE TITLE
TypeError with TS@5.1.3: Property 'hitsPerPage' does not exist on type 'IntrinsicAttributes & PlainSearchParameters'

### ISSUE THREAD

**Issue by jcwillox** [algolia/instantsearch#5658]
### 🐛 Current behavior

So this might be a bug with typescript, but it's the only library that broke when updating it so I'm going to create the bug report here.

When running with version `5.1.3` of `typescript` and `react-instantsearch-hooks-web` I get a type error on the `Configure` component, it appears it's no longer inferring the `SearchOptions` correctly. Downgrading to version `5.0.4` of `typescript` fixes the issue.

```tsx
> tsc --noEmit

components/SearchApp/SearchApp.tsx:28:18 - error TS2322: Type '{ hitsPerPage: number; filters: string | undefined; }' is not assignable to type 'IntrinsicAttributes & PlainSearchParameters'.
  Property 'hitsPerPage' does not exist on type 'IntrinsicAttributes & PlainSearchParameters'.

28       <Configure hitsPerPage={hitsPerPage} filters={filters} />
                    ~~~~~~~~~~~
```

### 🔍 Steps to reproduce

1. Install the following packages `react-instantsearch-hooks-web@6.44.1 typescript@5.1.3`
2. Create a component with
```tsx
<InstantSearch searchClient={searchClient} indexName={indexName}>
  <Configure hitsPerPage={hitsPerPage} filters={filters} />
  {children}
</InstantSearch>
```
4. Run `tsc --noEmit`

```
> tsc

components/SearchApp/SearchApp.tsx:28:18 - error TS2322: Type '{ hitsPerPage: number; filters: string | undefined; }' is not assignable to type 'IntrinsicAttributes & PlainSearchParameters'.
  Property 'hitsPerPage' does not exist on type 'IntrinsicAttributes & PlainSearchParameters'.

28       <Configure hitsPerPage={hitsPerPage} filters={filters} />
                    ~~~~~~~~~~~

```

Or checkout this repro https://stackblitz.com/edit/algolia-ts-bug-2mfs3u?file=app%2FSearchApp.tsx and run `npm run typecheck` in the terminal.

### Live reproduction

https://stackblitz.com/edit/algolia-ts-bug-2mfs3u?file=app%2FSearchApp.tsx

### 💭 Expected behavior

There should be no typescript error as with previous versions of typescript.

### Package version

react-instantsearch-hooks-web@6.44.1, typescript@5.1.3

### Operating system

Windows, Linux

### Browser

Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Haroenv** [comment]
I wonder if this is caused by PlainSearchParameters being extended from SearchOptions, but not manually retyping those keys? https://github.com/algolia/algoliasearch-helper-js/blob/develop/index.d.ts#L394

**Comment by jcwillox** [comment]
It seems the editor/typescript has trouble picking up the type of `SearchOptions` even when directly imported from `algoliasearch-helper/types/algoliasearch` and including it as a dependency. When importing `SearchOptions` directly from `@algolia/client-search` it does have the correct types but that's not surprising.

![image](https://github.com/algolia/instantsearch/assets/39120423/cea11ea6-b624-4a25-a354-e420cd59f730)

So perhaps its something to do with that `PickForClient` magic?

**Comment by jcwillox** [comment]
Currently, I'm just re-exporting the `Configure` component and including the `SearchOptions` type directly, which side-steps the issue without having to use `@ts-ignore` or type assertions.

```tsx
import { SearchOptions } from "@algolia/client-search";
import {
  Configure as ConfigureAlgolia,
  ConfigureProps,
} from "react-instantsearch-hooks-web";

export const Configure = (props: ConfigureProps & SearchOptions) => (
  <ConfigureAlgolia {...props} />
);
```

**Comment by Haroenv** [comment]
Thanks for listing this workaround, we didn't find that option yet!

**Comment by RobinSCU** [comment]
Hi @Haroenv,

thanks for the fix! Do you have an ETA for a release where the fix is included?

Have a great day!

**Comment by RobinSCU** [comment]
Thank you!

**Comment by g-mero** [comment]
Same issue on instantsearch.js

**Comment by Haroenv** [comment]
@g-mero, are you on the latest version of everything? This issue was fixed a couple months ago downstream

**Comment by Jorundur** [comment]
@Haroenv 

I've got a similar issue after migrating from v6 to v7.

Packages:

```json
  "react-instantsearch": "^7.4.1",
  "react-instantsearch-core": "^7.4.1",
```

Removed `@types` packages as per migration guide.

In a component I've got:

```tsx
import { Configure, InstantSearch, useInfiniteHits } from 'react-instantsearch'
```

(previously this was imported from `react-instantsearch-hooks-web`)

render:

```tsx
return (
    <div>
      <InstantSearch searchClient={searchClient} indexName={algoliaIndex}>
        <Configure filters={`productType:"${parentExpedition.productType}"`} hitsPerPage={4} />
        {/* irrelevant code removed */}
      </InstantSearch>
    </div>
  )
```

![Screenshot 2023-12-14 at 11 29 37](https://github.com/algolia/instantsearch/assets/5693633/d4ea2077-dc98-4cc0-b963-ff1fafc52222)

As mentioned above - the props type is `PlainSearchParameters` which doesn't have `filters`. Although `PlainSearchParameters` extends `SearchOptions`, `SearchOptions` doesn't have anything for `filters` either as far as I can see but I could be misunderstanding the `PickForClient` code.

Any ideas how to get this to work? I can see that the latest version (3.16.0) of `algoliasearch-helper` is being used.

**Comment by Haroenv** [comment]
I can't reproduce this in our examples, `filters` is correctly picked from `algoliasearch` (v4 and v3), we even have tests for it. If you can reproduce this consistently in a standalone environment, please create a sandbox, GitHub repo or similar and we can try to find the root cause @Jorundur

**Comment by Jorundur** [comment]
@Haroenv I just fixed this.

Had this warning when `yarn`-ing:

> "react-instantsearch > instantsearch.js@4.62.0" has unmet peer dependency "algoliasearch@>= 3.1 < 6".

Adding `algoliasearch` fixed this.

I didn't know that was required - it wasn't before when using v6 at least. So maybe it should be added to the migration guide? (Perhaps it's already there and I missed it).

**Comment by Haroenv** [comment]
It always was required, but in v6 there was no typescript types builtin. I believe v6 on DefinitelyTyped had a dependency on algoliasearch possibly though
