### ISSUE TITLE
JsDelivr CDN is down

### ISSUE THREAD

**Issue by sniperadmin** [algolia/instantsearch#5670]
### 🐛 Current behavior

All assets served via jsDelivr are not accessible:

Here are the themes and styles
https://cdn.jsdelivr.net/npm/instantsearch.css@8.0.0/themes/reset-min.css
https://cdn.jsdelivr.net/npm/instantsearch.css@8.0.0/themes/satellite-min.css

Same behavior happens with any other assets

### 🔍 Steps to reproduce

Just open the links by clicking them

### Live reproduction

N/A

### 💭 Expected behavior

serving assets

### Package version

8.0.0

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by aymeric-giraudet** [comment]
Hi @sniperadmin, seems like they fixed it, it's back already.

If the issue were to arise again, we don't own jsDelivr so there is nothing we could do about it but contact them.

Alternatively you can [install it from npm](https://www.npmjs.com/package/instantsearch.css) and bundle it with your app if you don't want to rely on jsDelivr.
