### ISSUE TITLE
Clarify/fix helper.derive docs

### ISSUE THREAD

**Issue by timkelty** [algolia/instantsearch#5708]
Trying to use a derived helper, a couple of things got me hung up [from the docs](https://community.algolia.com/algoliasearch-helper-js/reference.html#derive-multi-queries).

I wanted my derived helper to search on a new index. The `helper.derive` function states `The signature of the function is SearchParameters -> SearchParameters`. However, there is no mention in the docs of a `setIndex` method for `SearchParameters` (though it seems to work, and [what I need to use](https://github.com/algolia/algoliasearch-helper-js/issues/337#issue-169108447)).

Furthermore, the docs refer it firing the `results` event, when it should be `result`. PR here: https://github.com/algolia/algoliasearch-helper-js/pull/476

**Comment by Haroenv** [comment]
Ultimately advanced features of the helper like derive aren't encouraged as we will have a more straightforward way of debugging if it's done using InstantSearch. For that reason we won't add more documentation.
