### ISSUE TITLE
Nested array attributes are not highlighted

### ISSUE THREAD

**Issue by attila-csaszar** [algolia/instantsearch#5791]
### 🐛 Current behavior

I recently swittched from react instantsearch to hooks in hopes of getting rid of the exact issue mentioned here:
https://github.com/algolia/react-instantsearch/issues/2688

In short, attributes that are given as nested arrays in the Highlight widget do not get highlighted.

### 🔍 Steps to reproduce

Add a highlight widget to your app like so:

        <Highlight hit={hit} attribute="hierarchy.lvl1" />

### Live reproduction

https://codesandbox.io/s/nostalgic-diffie-2q54y3

### 💭 Expected behavior

All attributes should get highlighted, even if they are nested arrays.

### Package version

react-instantsearch-hooks-web@6.47.3

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Haroenv** [comment]
Hi @attila-csaszar, the reproduction you sent doesn't actually execute on codesandbox, so it's not straightforward what you actually mean with the issue.

Note that you can map over the individual items in the hierarchy if they are arrays: `{hit.hierarchy.lvl1.map((_, i) => <Highlight key={i} hit={hit} attribute={["hierarchy", "lvl1", i]} />}`

**Comment by attila-csaszar** [comment]
Hey, thanks for the quick reply.
I know it does not execute there. I am using the Docusaurus static html generator, and there the app works as a single .jsx page, I do not need any extra files other than the css.

I am a little new to all this, so could you elaborate on mapping over the items into hierarchy? What does this do exactly? Where should I put this in my code?
I tried and failed to find any info about this anywhere.
Thanks in advance.

**Comment by Haroenv** [comment]
If `hit.hierarchy.lvl1` is an array, and you want to display every item of the array, what you do is you replace:

```jsx
<Highlight hit={hit} attribute="hierarchy.lvl1" />
```

with

```jsx
{hit.hierarchy.lvl1.map((_, i) => <Highlight key={i} hit={hit} attribute={["hierarchy", "lvl1", i]} />}
```

so that you are looping over the items in the array, and create a highlight for each of the items in the array, this is similar to doing `hierarchy.lvl1[i]`
