### ISSUE TITLE
Algolia requires invalid router in next js 13 app directory

### ISSUE THREAD

**Issue by chrissshh** [algolia/instantsearch#5799]
### 🐛 Current behavior

The latest version of next.js 13 and algolia react-instantsearch-hooks-router-nextjs is incompatible because it requires that you import a router that only works with the old pages directory. To my understanding, nextjs uses { useRouter } from "next/navigation" when you need a router in a client component. Can you please recommend a fix to this issue? I would really appreciate any help.

"use client";
import { SingletonRouter } from "next/router";
import { createInstantSearchRouterNext } from "react-instantsearch-hooks-router-nextjs";

<InstantSearch  indexName="products" searchClient={searchClient}  routing={{ router: createInstantSearchRouterNext({           singletonRouter })}}>

### 🔍 Steps to reproduce

1. Use the latest next.js 13
2. Add reactinstantsearch-hooks-router-nextjs
3. Try to use this on a "use client" page or normal "server" page in the new "app" directory.
4. You'll get an error saying that next/router can't be used on anything other than a client page.

### Live reproduction

https://codesandbox.io

### 💭 Expected behavior

Work with { useRouter } or any other router option in the app directory of next js 13.

### Package version

react-instantsearch-hooks-router-nextjs 6.4.73

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by aymeric-giraudet** [comment]
Hey @chrissshh,

This is because the custom router was made for the `pages` directory router.

From my experience when doing CSR with the `app` dir, simply having `<InstantSearch routing={true}>` works out of the box as Next.js no longer relies on having a specific key in history to know whether it should rerender when back/forward browser button has been pressed.

Can you please tell me what's not working with `routing={true}` ?

The reason we don't document it is that we still don't support SSR with the `app` dir, but maybe it's worth documenting that for CSR.

**Comment by LarsEjaas** [comment]
Is there anywhere you can find a guide on how to sync query variables with the next URL in the nextjs App router? I am unsure how to this really. I use Algolia for search functionality only inside a modal, so everything is running clientside.

**Comment by aymeric-giraudet** [comment]
Hey @LarsEjaas, as we're not currently officially supporting the app router, there is none yet.
Could you provide a CodeSandbox showcasing what are the exact problems you have so that we can provide a workaround and/or take that into account when we officially support the app router ?

**Comment by LarsEjaas** [comment]
Hi @aymeric-giraudet Thanks for taking the time to help 🙂  
Well, I have the same issue with the page router in Nextjs also actually - I am unsure how to sync the query variables with the URL(and still be able to navigate back and forth in the history of the Nextjs router).
I am looking at this page:
https://www.algolia.com/doc/api-reference/widgets/instantsearch-next-router/react/
Here it is explicitly stated that:
`createInstantSearchNextRouter() is a function that creates a Next.js-compatible InstantSearch router to pass to InstantSearch... ...This function cannot be used in conjunction with getStaticProps. Use getServerSideProps() or client-side rendering instead.`
So, my issue is that I would like to be able to render my Algolia search clientside only where everything else on the page is statically rendered. That was fairly easy to do with React InstantSearch v6. But in v7 I have a hard time figuring out how to do this. In v6 I just had the full search in a modal and all the Algolia javascript would lazyload when the user opened the modal. That also works really well in v7 - but figuring out how to sync the query parameters with the URL is a struggle.
Do you do it without using createInstantSearchNextRouter() at all? I am a bit lost...

**Comment by ddaoxuan** [comment]
Hey @aymeric-giraudet  do you guys have an ETA by any chance on App router support?
Is it something currently on your roadmap?

**Comment by Haroenv** [comment]
It's definitely on our roadmap and we're actively working on it (see POCs in #5828 and #5827), but we have no timeline on this as of yet.
