### ISSUE TITLE
vue-instantsearch: Passing percentage units to the global abs() function is deprecated.

### ISSUE THREAD

**Issue by paceband** [algolia/instantsearch#5810]
### 🐛 Current behavior

npm run prod generates:
transforming (327) node_modules\vue-instantsearch\vue3\es\src\components\Menu.vue_vue&type=script&lang.jsDeprecation Warning: Passing percentage units to the global abs() function is deprecated.
In the future, this will emit a CSS abs() function to be resolved by the browser.
To preserve current behavior: math.abs(100%)
To emit a CSS abs() now: abs(#{100%})
More info: https://sass-lang.com/d/abs-percent

### 🔍 Steps to reproduce

npm run prod

### Live reproduction

https://not

### 💭 Expected behavior

No warning

### Package version

vue-instantsearch 4.8.4

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by dhayab** [comment]
Hi, the Menu widget and in general Vue InstantSearch don't depend on Sass. Maybe this issue comes from another dependency in your application stack? I'll close this issue for now, but feel free to reopen it with a link to a reproducible sandbox if you confirm it's relevant to this library.
