### ISSUE TITLE
The way to select attributes for faceting or attributes to display is not clear

### ISSUE THREAD

**Issue by rogerximenez** [algolia/instantsearch#5846]
### 🐛 Current behavior

I recently noticed that --attributes-for-faceting requires the customer to select an item by tapping the space bar… but if I navigated to an attribute and clicked Enter, it’ll create the app without adding the facet to the InstantSearch app. 

### 🔍 Steps to reproduce

1. Open your terminal
2. Run `create-instantsearch-app`
3. Navigate towards `--attributes-for-faceting` or `--attributes-to-display`
4. Notice that if the customer hovers over an item and clicks the _Enter_ or _Return_ key on their keyboard, it'll complete the step without selecting an item. It's not directly evident the customer must select _Space_ to make their multi-selection.

### Live reproduction

not applicable

### 💭 Expected behavior

It should be more clear how to make a selection. Customer should explicitly select "none" instead of treating an _Enter_ without anything selected as "none". Ideally, it would be directly evident how to select things.

### Package version

Latest version of react

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Haroenv** [comment]
even though it says "press space to select"? this is the default inquirer behaviour
<img width="1003" alt="Screenshot 2023-09-13 at 13 30 43" src="https://github.com/algolia/instantsearch/assets/6270048/f5eb9d38-6ce7-4b28-a9e5-ea996390ab36">
