### ISSUE TITLE
Insights triggering too many requests and blocking the user thread. (CORB).

### ISSUE THREAD

**Issue by bernardinorafael** [algolia/instantsearch#5862]
### 🐛 Current behavior

I noticed a behavior that curiously only happens in RefinementList, and more specifically when cleaning the search and resending information.

The browser is throwing the following error: "Refused to set unsafe header Content-Length".

You may also notice some error messages reporting CORB problems.

![image](https://github.com/algolia/instantsearch/assets/102430354/5c4f8b54-f24f-4bc0-895f-67bddf8d43a5)

### 🔍 Steps to reproduce

1  - Go to https://marketplace.xyami.co.ao/search
2 - Use some faceted search filters and inspect the browser.

### Live reproduction

https://marketplace.xyami.co.ao/search

### 💭 Expected behavior

No errors when re-searching when clearing RefinementList components

### Package version

react-instantsearch: 7.1.0, react-instantsearch-core: 7.1.0

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by sacr3dc0w** [comment]
Encountering the same, though in our use case, there's no use of RefinementList.

**Comment by bernardinorafael** [comment]
@sacr3dc0w 

I totally forgot about this issue.

my problem was related to a call to useInfiniteQuery, which was interfering with useRefinementList queries, I have already resolved this problem.

**Comment by maderesponsively** [comment]
How did you resolve this? @bernardinorafael

**Comment by scottkelso** [comment]
@sacr3dc0w I'm seeing these same errors when using `useInfiniteHits` only on the `showMore` call. 

I'm using 
```
"instantsearch.js": "^4.63.0", 
"react-instantsearch": "^7.5.0", 
"react-instantsearch-router-nextjs": "^7.12.3"
```
in a nextjs 14.2.3 app.

Could this be an issue with algolia or might I also have a conflict?
