### ISSUE TITLE
Extra client-side call being made when navigating to Algolia page (Next 13, pages dir)

### ISSUE THREAD

**Issue by KarinMeijvogel** [algolia/instantsearch#5864]
### 🐛 Current behavior

When using the [boilerplate code](https://github.com/algolia/instantsearch/tree/master/examples/react/next), navigating from a simple page to a page using InstantSearch, unwanted Algolia requests appear in the network tab in the browser:

<img width="1611" alt="Scherm­afbeelding 2023-09-22 om 16 51 13" src="https://github.com/algolia/instantsearch/assets/110387333/942e8d50-d9fb-4529-988e-9b2dda87fca2">

**In my older projects where I'm using NextJS 12, this issue does not occur. The page simply loads without a client-side call to algolia.**

### 🔍 Steps to reproduce

1. From the homepage, click on the "Go to algolia page" link
2. Notice how a new Algolia request appears in the network tab, as soon as the Algolia page loads

### Live reproduction

https://codesandbox.io/p/sandbox/focused-hoover-z58yzs?file=%2Fpages%2Fsearch.tsx%3A21%2C10-21%2C15

### 💭 Expected behavior

No client-side algolia call when switching between pages.

### Package version

instantsearch 7.1.0, next 13.5.1

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

**Comment by Haroenv** [comment]
This should be fixed in https://github.com/algolia/instantsearch/pull/5854 I believe, can you try that out?

**Comment by KarinMeijvogel** [comment]
@Haroenv It's my first time actually making an issue, so forgive my ignorance, but changing my package.json to the following did indeed help! (Although I'm not sure if this is the correct way to test it):
```
{
  "name": "example-react-instantsearch-next-example",
  "version": "11.0.0",
  "private": true,
  "scripts": {
    "dev": "next dev",
    "build": "next build",
    "start": "next start",
    "lint": "next lint"
  },
  "dependencies": {
    "algoliasearch": "4.14.3",
    "instantsearch.css": "8.1.0",
    "next": "13.5.1",
    "react": "18.2.0",
    "react-dom": "18.2.0",
    "react-instantsearch": "https://pkg.csb.dev/algolia/instantsearch/commit/432a6884/react-instantsearch",
    "react-instantsearch-router-nextjs": "7.1.0"
  },
  "devDependencies": {
    "@types/node": "17.0.40",
    "@types/react": "18.0.12",
    "eslint": "8.4.0",
    "eslint-config-next": "12.0.7",
    "typescript": "5.1.3"
  }
}
```
