### ISSUE TITLE
Attribute widget is not displays active filter when use the filters config

### ISSUE THREAD

**Issue by bilalmalkoc** [algolia/instantsearch#5891]
### 🐛 Current behavior

When set the a filter with configure widget, current filters not displaying as active.

I set `brand:Apple` filter here:

```
instantsearch.widgets.configure({
  hitsPerPage: 8,
  filters: 'brand:Apple',
}),
```

### 🔍 Steps to reproduce

1. Go to sandobx,
2. Check the menu widget.

### Live reproduction

https://codesandbox.io/s/ecstatic-lovelace-hfqwqw?file=/src/app.js:641-730

### 💭 Expected behavior

In the menu widget, Apple brand must be selected because i set this attribute from config widget.

### Package version

instantsearch.js 4.57.0

### Operating system

macOS 14.0

### Browser

Google Chrome 117.0.5938.149

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

**Comment by dhayab** [comment]
Hi, the `configure` widget does not apply search parameters to the UI. If you want to have a refined UI, you need to additionally set [`initialUiState`](https://www.algolia.com/doc/api-reference/widgets/instantsearch/js/#widget-param-initialuistate) in `instantsearch()`, like this:

```js
const search = instantsearch({
  // ...
  initialUiState: {
    instant_search: {
      menu: {
        brand: 'Apple'
      }
    }
  }
});
```
