### ISSUE TITLE
Hierarchicalmenu: Amount of results displayed per root category is wrong when navigating to level 3

### ISSUE THREAD

**Issue by hereischris** [algolia/instantsearch#5896]
### 🐛 Current behavior

When using the hierarchicalmenu widget and navigating to a level 3 category from a particular root category, the amount of results  which is displayed next to the category name of the root category is wrong.

It picks up the number of the results of the second level category.
This does not happen when navigating to level 2.
It even happens in Algolias own storybook (link attached below).

### 🔍 Steps to reproduce

1. Go to hierarchicalmenu storybook page  in default mode: https://instantsearchjs.netlify.app/stories/js/?path=/story/refinements-hierarchicalmenu--default
2. Click on Cameras & Camcorders
3. Click on Camcorder Accessories
4. Click on Action Camcorder Chargers
5. See the number of results next to Cameras & Camcorders change to 173

### Live reproduction

https://instantsearchjs.netlify.app/stories/js/?path=/story/refinements-hierarchicalmenu--default

### 💭 Expected behavior

The number should remain stable. (1369 in our example case)

### Package version

instantsearch 7.2.0

### Operating system

Windows 10 Pro

### Browser

Google Chrome 117

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by dhayab** [comment]
Hi, you can set the [`future.persistHierarchicalRootCount`](https://www.algolia.com/doc/api-reference/widgets/instantsearch/js/#widget-param-persisthierarchicalrootcount) in your InstantSearch widget to prevent refinements from updating the count dispayed at the refined root level.

**Comment by Haroenv** [comment]
Ah yes that also has a similar option: https://github.com/algolia/instantsearch/blob/54978fec1b62fa0ed493274dcf880263d79b6e43/packages/algoliasearch-helper/index.d.ts#L1182

With that confirmation I'll close this issue, thanks for "reviving" it to make us aware :)
