### ISSUE TITLE
[Bug] - Issue with your exported types when upgrading to V7

### ISSUE THREAD

**Issue by joelpierre** [algolia/instantsearch#5897]
### 🐛 Current behavior

I used the codemod and also attempted to manually solve the issue however my editor and TS itself is very confused with your types: 

```
import {
  type InstantSearchProps,
  useHits,
  type UseHitsProps,
  usePagination,
  type UsePaginationProps,
  connectMenu, <-- This doesn't exist apparently
  connectSearchBox, <--- This doesn't exist either
} from 'react-instantsearch'
```

<img width="1014" alt="Screenshot 2023-10-17 at 14 14 17" src="https://github.com/algolia/instantsearch/assets/8969851/daa7f56b-54c2-47e8-8f18-2ada95ca70f1">

This also failed in the terminal 

<img width="754" alt="Screenshot 2023-10-17 at 14 18 29" src="https://github.com/algolia/instantsearch/assets/8969851/d0c42430-1478-46db-a6ed-a0c6a5130e8d">

I can ts-ignore this and it all works fine so you do "actually export it" but your types are not playing ball at all...

I then installed your core package and it also doesn't export those two functions 🤔 ... so I tried accessing the index file directly from the core package ...

<img width="649" alt="Screenshot 2023-10-17 at 14 14 42" src="https://github.com/algolia/instantsearch/assets/8969851/e2893af8-e43c-4134-938a-240a17749848">

And all good... so there is something up with how you export the types.

### 🔍 Steps to reproduce

Setup a new TS project 
Install new V7 react-instantsearch pkg and try to use `connectMenu` or `connectSearchBox` <- These are the only two I needed, there may be more.

### Live reproduction

https://codesandbox.io/s/cool-fast-lfppn7?file=/src/App.tsx

### 💭 Expected behavior

I expect the types to be exported from the right place, and I don't expect to have to install the core library separately as your docs state that they are re-exported from the react-instantsearch pkg

### Package version

7.2.0

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Haroenv** [comment]
While the connectors aren't totally the same, you should import them from `instantsearch.js/es/connectors` instead of from `react-instantsearch`. In most cases you should be able to use `useMenu`, `useSearchBox` instead of the connectors directly. What are you using them for exactly? 

Could you maybe share the code before transformation/codemod so we can see if it can be automatically changed?

**Comment by joelpierre** [comment]
Hi I was just following your docs in which it states that all imports from the specific packages "-dom, -web, -server", can be moved to just `react-instantsearch`, which isn't the case, so at the least the docs should be updated to specify that it isn't the case. Also instantsearch.js is a separate package so I wouldn't assume to take it from there instead given the docs explanation.

Happy to move to `useMenu` and `useSearchBox` for our use case for sure (and I have done so) but the issue still stands with regards to the types. The sandbox output was very similar to how we were using it (not sure why tbh).

The codemod only changed the import for this particular thing so nothing really to share.

**Comment by Haroenv** [comment]
So the code you used to have before the codemod was: 

```js
import {
  connectMenu,
  connectSearchBox,
} from 'react-instantsearch-core';

export const ExampleConnectMenu = () => {
  connectMenu(() => null);
  return null;
};

export const ExampleConnectSearchBox = () => {
  connectSearchBox(() => null);
  return null;
};
```

Because I don't think this (is meant to) work. With `use` however that code makes sense

The type issue exists as React InstantSearch _doesn't have_ connectMenu or connectSearchBox, so it can't export those types of couse

**Comment by joelpierre** [comment]
We didn't have core before it was v6 `react-instantsearch-dom` as below:

```ts
import { connectMenu, connectSearchBox } from 'react-instantsearch-dom'
```

and it changed it to 

```ts
import { connectMenu, connectSearchBox } from 'react-instantsearch'
```

which is what my IDE auto completes to as well... and if I ts-ignore it all works fine and if I log out the function it exists but the types don't allow for it (which may be what you want even though it is technically exported) if I used vanilla JS it would work fine.

There may be an issue in react-instantsearch however in which you re-export everything/or some funcs from `react-instantsearch-core`. Or module naming clashes etc 🤷🏽 I dunno but importing like the below doesn't work either

```ts
import {
  connectMenu,
  connectSearchBox,
} from 'react-instantsearch-core';
```

**Comment by Haroenv** [comment]
Again, connect* doesn't exist in v7, that's what could be made more clear in the migration script though. Thanks for your feedback!

**Comment by joelpierre** [comment]
> Again, connect* doesn't exist in v7, that's what could be made more clear in the migration script though. Thanks for your feedback!

Sorry you may say this but it is there. So I would check the code and make sure... on checking react-instantsearch v7.2.0 you in-fact export everything from core, so one would expect not to have to install core at all and use `react-instantsearch` only.

<img width="698" alt="Screenshot 2023-10-18 at 12 44 26" src="https://github.com/algolia/instantsearch/assets/8969851/0c7002e2-56e9-4510-b5ff-b869b3249cd9">

the below is a lot of connect functions considering they don't "exist" for v7 these functions are also **usable** but fail type checking.
<img width="525" alt="Screenshot 2023-10-18 at 12 45 15" src="https://github.com/algolia/instantsearch/assets/8969851/ce0cdc43-d9f8-4a4b-8736-36c4b97ef98d">

the below is your react-instantsearch-core types which indeed export connect* function type declarations
<img width="1279" alt="Screenshot 2023-10-18 at 12 47 15" src="https://github.com/algolia/instantsearch/assets/8969851/7bc4c099-ff60-417f-be6e-910b7abb80a1">

So I appreciate your intention is that they don't exist... but they very much do and make your docs a TON more confusing... at the least this is a bug and not expected behaviour on either my part as the consumer reading your docs and your part as you say they shouldn't exist at all in v7 😅

**Comment by Haroenv** [comment]
Do you still have a React InstantSearch Core v6 installed? I can't reproduce this in the sandbox 🤔

**Comment by joelpierre** [comment]
> Do you still have a React InstantSearch Core v6 installed? I can't reproduce this in the sandbox 🤔

Its in the sandbox on this issue https://codesandbox.io/s/cool-fast-lfppn7?file=/src/App.tsx if you remove the `connect*` imports and do the usual cmd + spacebar then you will see it has connect in the exports of `react-instantsearch` and so on.

**Comment by Haroenv** [comment]
<img width="535" alt="Screenshot 2023-10-18 at 15 17 28" src="https://github.com/algolia/instantsearch/assets/6270048/ff131e05-091d-4598-8921-e185c5aa0ff6">

oddly I'm not seeing that. Maybe you're having that locally because you used to have React InstantSearch v6 installed and typescript still somehow has that indexed. 

React InstantSearch Core also only has the correct imports:

<img width="546" alt="Screenshot 2023-10-18 at 15 18 42" src="https://github.com/algolia/instantsearch/assets/6270048/931cbffa-e203-4982-a76b-2449572f453d">

Both of those screenshots were from a clean download of the sandbox you linked 🤔

**Comment by joelpierre** [comment]
Really weird because that sandbox links shows me this

![Screenshot 2023-10-18 at 14 34 43](https://github.com/algolia/instantsearch/assets/8969851/bc5615e0-01e4-4b03-b1f4-410648123ae5)

I only used v7.2 in the deps in this sandbox too. 😅

**Comment by Haroenv** [comment]
The top two suggestions aren't from TypeScript, but from "other words also in the file". If you removed instead of copied those suggestions won't show up :)

**Comment by jdnichollsc** [comment]
Hey folks, hope you're doing well

Any example to replace the connectMenu utility?
Thanks for your support! <3

**Comment by jdnichollsc** [comment]
@joelpierre are you using that from a new React Native project? 🤔

**Comment by jdnichollsc** [comment]
@Haroenv oh Is there any example? I don't see anything here: https://www.algolia.com/doc/guides/building-search-ui/going-further/native/react/

**Comment by Haroenv** [comment]
useMenu is pretty much the same as useRefinementList, so this example: https://www.algolia.com/doc/guides/building-search-ui/going-further/native/react/#filter-with-a-refinement-list-in-a-modal @jdnichollsc, also a DOM example here you can translate to react native: https://www.algolia.com/doc/api-reference/widgets/menu/react/#hook-example

**Comment by aymeric-giraudet** [comment]
Hi @joelpierre,

First, did you run the codemod against your `.tsx` files ? By default it seems like it doesn't pick up `.ts` files, so you should use it like so : 
```sh
npx @codeshift/cli --packages 'instantsearch-codemods#ris-v6-to-v7' src/**/*.tsx
```

When I do this on a file importing `connectMenu` from `react-instantsearch-dom`, it does get replaced to `useMenu` from `react-instantsearch`, and it even outputs a HoC called `connectMenu` along with a TODO message : 

<img width="882" alt="image" src="https://github.com/algolia/instantsearch/assets/9158954/e3eb3265-fa22-42b6-b0f7-b07fd0d66339">

Regarding your type errors, can you show the contents of `package.json` in `react-instantsearch-core` ?
You can also run this command in the terminal : `head node_modules/react-instantsearch-core/package.json`

You could also link a `package-lock.json`, `yarn.lock` or `pnpm` lock file if you're using it.

Thank you !

**Comment by joelpierre** [comment]
Hey @aymeric-giraudet thanks for getting back to me and for the suggestion. I ending up refactoring a ton of the code a couple weeks back so this issue isn't as pressing. Looking in my pnpm-lock file there were no other react-instantsearch pkg versions so not sure why it said they were there. I even screenshotted the type defs from the pkg inside 7.2.0 so not sure why there are so many differing results (maybe you are on 7.2.X and not 0).

To help you guys debug here is our lock file (had to upload as a zip)
[pnpm-lock.yaml.zip](https://github.com/algolia/instantsearch/files/13336341/pnpm-lock.yaml.zip)

The reason I don't just think it's my IDE or something weird is because I nuked my node_mods and the cache a lot before re-installing and I still came up with the above screenshots 🤷🏽‍♂️  but yeah I dunno anymore 😅

**Comment by Haroenv** [comment]
we've updated the documentation now to ensure tsx extension is processed, it should all work as expected. Thanks for your feedback
