### ISSUE TITLE
Algolia Support for Angular InstantSearch

### ISSUE THREAD

**Issue by loveraimogen** [algolia/instantsearch#5924]
> [!IMPORTANT]
> For an update on this topic, please read [this comment](https://github.com/algolia/instantsearch/issues/5924#issuecomment-2152881610).

### Background
Angular has evolved significantly with the [removal of the legacy view engine in favor of Ivy](https://github.com/algolia/angular-instantsearch/issues/994), and the ecosystem is continuously advancing, as seen with the recent release of Angular v17. This has brought up questions about Algolia’s future support of angular-instantsearch.

### Update
We are aware of the challenges and the importance of this library to your projects and are currently evaluating the best path forward, considering the complexities involved with updating the library to be fully compatible with the latest Angular version.

We want to ensure that we approach this transition thoughtfully and effectively and we invite you to share your thoughts on the library's importance to your work and any specific challenges you're facing due to the current compatibility issues. 

### Feedback
If you have suggestions or are willing to contribute to the library's development, **we're open to reviewing pull requests**.

Please use this issue to share your feedback, ideas, and any contributions you might have. Your input is crucial as we navigate the future of Angular InstantSearch.

**Comment by johan--** [comment]
Angular has moved on to v17, the issue remains a stumbling block. This is the error given when compiling an Angular v16 or v17 application:

```
Error: src/app/app.module.ts - error NG6002: 'NgAisModule' does not appear to be an NgModule class.

This likely means that the library (angular-instantsearch) which declares NgAisModule is not compatible with Angular Ivy. Check if a newer version of the library is available, and update if so. Also consider checking with the library's authors to see if the library is expected to be compatible with Ivy.
```

**Comment by adamunchained** [comment]
Feedback is simple, make sure angular-instantsearch supports latest Angular.

**Comment by tgangso** [comment]
Clear communication on whether or not you plan on updating this library to support angular going forward is key.

**Comment by willem** [comment]
Just adding my 2 cents in support of the importance of ensuring that angular-instantsearch works with the latest version of Angular. Angular is a very widely used web development framework and the angular-instantsearch is certainly a good motivation/reason to use Algolio for these web apps. angular-instantsearch is one of the main reasons why we decided to use Algolio. Thanks!

**Comment by No1e** [comment]
Never going to happen. We are waiting for so long. I decided to give up and implement my own UI components that communicates through my "proxy" Web API that uses Algolia API. It is slightly slower but its not noticeable.

**Comment by u-cole** [comment]
This is such an important issue... Angular latest versions bring big advantages and if we cannot use instantsearch then it is a huge blow to both communities

**Comment by moufidagmmd** [comment]
When I was in the process of using Angular 16, I have problems with the compatibility between Angular 16 and Angular-instantsearch, are there any news about this problem?

**Comment by sbacem** [comment]
We selected Algolia, more precisely the InstantSearch module; however, this choice posed significant challenges for both me and my clients. The problem comes from the inability to update to the latest version. Without a comprehensive plan in place, we find ourselves forced to explore alternative solutions. Despite all the investments made with algolia

**Comment by siwarsel** [comment]
Our company is responsible for the development of several high-traffic dynamic websites, all utilizing Algolia and Angular. Unfortunately, we continue to face significantly long page loading times. This is why the migration to Angular versions v16 and v17 has become an urgent necessity that cannot be further delayed. At the same time, it is crucial for us to maintain our use of Algolia. We have been stuck in this situation for several months, and it is creating a risky dynamic with our clients. We urgently request you to update Angular InstantSearch as soon as possible so that we can significantly enhance the development of our websites. Thank you for taking swift action to address this issue.

**Comment by Shamshiel** [comment]
Are there any updates or progress to share on this issue? Will this ever be implemented or are newer versions of Angular basically excluded from using Algolia (or everything that relies on InstantSearch)?

**Comment by SothiKhorn019** [comment]
Hopefully, the team will update angular-instantsearch to supports with the latest Angular version.

**Comment by nskoro** [comment]
This is a major issue. Please let us know if you plan to support angular.

**Comment by ajaypond** [comment]
Definitely want to see InstantSearch supported in the latest Angular. Would be a major setback to our progress using Algolia if we lost InstantSearch

**Comment by u-cole** [comment]
Any further decisions here : I really need this to happen or i need to look at alternatives

**Comment by adamunchained** [comment]
> Any further decisions here : I really need this to happen or i need to look at alternatives

Clearly this does not seems to be a priority. You should consider switching to another provider. This has pretty much screw us (waiting for months) and made us a realize that Algolia team is not ready to support you here. We started migration to another tool and it isn't that scare as we thought. With Algolia pricing we will actually save money over time anyways...

**Comment by tgangso** [comment]
The lack of communication clearly means it is not being worked on sadly.

**Comment by syahirudean** [comment]
> > Any further decisions here : I really need this to happen or i need to look at alternatives
> 
> Clearly this does not seems to be a priority. You should consider switching to another provider. This has pretty much screw us (waiting for months) and made us a realize that Algolia team is not ready to support you here. We started migration to another tool and it isn't that scary as we thought. With Algolia pricing we will actually save money over time anyways...

Any good recommendation?

**Comment by willem** [comment]
We are prepared to assist in getting Angular InstantSearch working again with the latest versions of Angular. My colleague @johan-- , a competent and experienced Angular developer, has been going through the instantsearch code extensively and he has made some changes and has submitted a Pull request more than a month ago already, without any response yet from Algolio. In the [Pull request](https://github.com/algolia/angular-instantsearch/pull/1006) he also requires input from Algolia to be able to make further progress. No feedback has yet been received. 
@loveraimogen please provide feedback regarding the priority and future of Angular InstantSearch.

**Comment by xXCalleManXx** [comment]
I'm working on a big enterprise webshop, which have used this library for a long time. This library have hold us back from upgrading from Angular 15 and up, but when I was reading this comment from NateMay, it was clear for me that the best idea is to ditch this library completely for our own sake and also for future upgrades. https://github.com/algolia/angular-instantsearch/issues/994#issuecomment-1546702092

With few weekly downloads, I don't believe that the Algolia team will ever prioritize this project.

**Comment by u-cole** [comment]
> I'm working on a big enterprise webshop, which have used this library for a long time. This library have hold us back from upgrading from Angular 15 and up, but when I was reading this comment from NateMay, it was clear for me that the best idea is to ditch this library completely for our own sake and also for future upgrades. [algolia/angular-instantsearch#994 (comment)](https://github.com/algolia/angular-instantsearch/issues/994#issuecomment-1546702092)
> 
> With few weekly downloads, I don't believe that the Algolia team will ever prioritize this project.

Im coming to the same conclusion...

I actually use Meilisearch not Algolia. Meilisearch can be self-hosted with no cost. It doesn't have all the features of Algolia but is extremely fast and has core features you will need for a very good search experience. 

You can see it in action here : https://www.ultraislife.com/en/uniqs/marketplace

Meilisearch makes use of the instantsearch libraries but I am now spending time building the UI myself and wiring it to the Meillisearch api. It isn't as much work as I maybe thought and this will allow me to remove instantsearch dependencies and upgrade angular

**Comment by gak112** [comment]
> algolia/angular-instantsearch#994 (comment). 
 


better to create own components by installing algoliasearch

created service

import { Injectable } from '@angular/core';
import algoliasearch from 'algoliasearch';
import { environment } from '../../environments/environment.development';

const client = algoliasearch(environment.AAPPID, environment.AAPIKEY);

@Injectable({ providedIn: 'root' })
export class AlgoliaService {
    constructor() { }


    async search(indexName: string, query: string) {
        const index = client.initIndex(indexName);
        return await index.search(query);
    }

    async searchByPage(indexName: string, query: string, page: number, hitsPerPage: number) {
        const index = client.initIndex(indexName);
        return await index.search(query, {
            page: page,
            hitsPerPage: hitsPerPage
        });
    }

    async getFilterQueryHits(indexName: string, filter: string, query: string) {
        const index = client.initIndex(indexName);
        return await index.search(query, {
            filters: filter
        });
    }
    /* (NUMERIC RANGE : price:5.99 TO 100) (NUMERIC OPERATORS - <, <=, =, !=, >=, >, EX: price > 12.99)
     other operators: AND, OR, NOT, TO
    Supported: facet:value1 OR facet:value2, num=1 OR num=2
    Unsupported: facet:value OR num=3 OR tag1
    upported: filter1 AND (filter2 OR filter3)
    Unsupported: filter1 OR (filter2 AND filter3).
    array example: genres: ["fiction", "thriller", "sci-fi"]
    price < 10 AND (category:Book OR NOT category:Ebook)
    dateFilter: filters: `date_timestamp > ${Math.floor(d.setDate(d.getDate() - 365) / 1000)}`
    filters: 'attribute:value [AND | OR | NOT](#boolean-operators) attribute:value'
    'numeric_attribute [= | != | > | >= | < | <=](#numeric-comparisons) numeric_value'
    'attribute:lower_value TO higher_value'
    '[facetName:facetValue](#facet-filters)'
    '_tags:value'
    'attribute:value' */
    async getFilterQueryHitsByPage(indexName: string, filter: string, query: string, page: number, hitsPerPage: number) {
        const index = client.initIndex(indexName);
        return await index.search(query, {
            page: page,
            hitsPerPage: hitsPerPage,
            filters: filter
        });
    }

    async getFacetFilters(indexName: string, query: string, facetFilters: string) {
        const index = client.initIndex(indexName);
        return await index.search(query, {
            facetFilters: facetFilters
        });
    }

    async getFacetFiltersByPage(indexName: string, query: string, facetFilters: string, page: number, hitsPerPage: number) {
        const index = client.initIndex(indexName);
       return await index.search(query, {
            page: page,
            hitsPerPage: hitsPerPage,
            filters: facetFilters
        });
    }



    async getFacets(indexName: string, query: string, facets) {
        const index = client.initIndex(indexName);
        return await index.search(query, {
            facets
        });
    }

    async getFacetValues(indexName: string, query: string, facet, facetValueQuery?: string) {
        const index = client.initIndex(indexName);
        return await index.searchForFacetValues(facet,facetValueQuery, {
            facetFilters: query
        });
       // index.search
    }

    async getObject(indexName: string, objectID: string) {
        const index = client.initIndex(indexName);
        return await index.getObject(objectID);

    }

    async getObjects(indexName: string, objectIDs: string[]) {
        const index = client.initIndex(indexName);
        return await index.getObjects(objectIDs);

    }

    async saveObject(indexName: string, object: any) {
        const index = client.initIndex(indexName);
        const result = await index.saveObject(object).wait();
        return result;
    }

    async saveObjects(indexName: string, objects: any) {
        const index = client.initIndex(indexName);
        const result = await index.saveObjects(objects, { autoGenerateObjectIDIfNotExist: true }).wait();
        return result;
    }

    async updateObject(indexName: string, object: any) {
        const index = client.initIndex(indexName);
        const result = await index.partialUpdateObject(object, { createIfNotExists: false }).wait();
        return result;
    }

    async updateObjects(indexName: string, objects: any) {
        const index = client.initIndex(indexName);
        const result = await index.partialUpdateObjects(objects).wait();
   
        return result;
    }

    async deleteObject(indexName: string, objectID: string) {
        const index = client.initIndex(indexName);
        const result = await index.deleteObject(objectID).wait();
        return result;
    }

    async deleteObjects(indexName: string, objectIDs: string[]) {
        const index = client.initIndex(indexName);
        const result = await index.deleteObjects(objectIDs).wait();
        return result;
    }




    //queryObject style = {indexName: "indexName", query: "query", params: {hitsPerPage: 5}}
    async getMultipleQueries(queries){
        return await client.multipleQueries(queries);
    }

    async refresh() {
        client.clearCache();
    }

}

**Comment by mspriggs** [comment]
Angular InstantSearch is a key component of our ticketing system. Please support current versions of Angular as soon as possible. We are now two versions behind.

**Comment by u-cole** [comment]
@loveraimogen is their any indication from the team about what is happening with this issue?

**Comment by gigadie** [comment]
The Ivy Engine became the default Angular compiler with the release of Angular v9, released in February 2020. That's more than 4 years ago. It's a bit worrying in a fast paced reality as the FE world is, nothing has been planned since then to migrate to a more modern version which supported Ivy.

**Comment by FunkMonkey33** [comment]
It's too bad your website stated (until quite recently) that Angular Instant Search was compatible with the latest versions of Angular.  I wouldn't have upgraded our Angular version at that time.  Unfortunately your website was misleading, or just an outright lie, and I did the upgrade, then had to replace all of our Algolia widgets with our own components and instantsearch.js API calls.   Cost me about 100 hours that I can't get back.

**Comment by chrisvanderkooi** [comment]
Pretty disappointing that Algolia is not supporting Angular 15+. Our application has utilized Algolia and specifically this package for over 4 years and as we worked to upgrade our Angular app, we come to find that this library is not being actively maintained and cannot use it with Ivy. +1 to make this package compatible with Ivy... but, we will have moved off this package and probably Algolia by then.

**Comment by torusservices** [comment]
Please dedicate some resource to this
