### ISSUE TITLE
deserializeQueryParameters - TypeError: Cannot read properties of undefined (reading 'split')

### ISSUE THREAD

**Issue by volodymyr-strilets-mindcurv** [algolia/instantsearch#5964]
## Unhandled Runtime Error

![image](https://github.com/algolia/instantsearch/assets/101807528/f79408e4-b2c6-4393-95a8-2a0188faa391)

## Here is the line of the error code 👇

![image](https://github.com/algolia/instantsearch/assets/101807528/3a972c69-0bf2-4220-9649-f2de4dcbe602)

## Localhost console debug

Did a quick debug and found that the `result` item from `deserializeQueryParameters` has no `params` key. 

![image](https://github.com/algolia/instantsearch/assets/101807528/f3d945fc-a614-4582-b8f7-5d1f6a75ce64)

### 🔍 Steps to reproduce

I have updated the libraries and this error appeared

algoliasearch: 4.20.0 > 4.21.1 
instantsearch.js: 4.58.0 > 4.62.0
react-instantsearch: 7.2.0 > 7.4.1
react-instantsearch-core: 7.2.0 > 7.4.1
react-instantsearch-router-nextjs: 7.2.0 > 7.4.1

### Live reproduction

-

### 💭 Expected behavior

Working code

### Package version

react-instantsearch: 7.4.1, react-instantsearch-core: 7.4.1, react-instantsearch-router-nextjs: 7.4.1, instantsearch.js: 4.62.0, algoliasearch: 4.21.1

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Haroenv** [comment]
Hm, that should indeed be made safe, however, how do you end up in a situation where `params` isn't in the result. Is it manually filtered out by you? If there's no `params`, I'm sure that the cache will not work. Safe solution would be bailing out of writing the cache altogether in that case.

Do you have a reproducible example?

**Comment by volodymyr-strilets-mindcurv** [comment]
We have NextJS SSR and we use hooks from `react-instantsearch` as they are. 
I have checked the initial server state that `getServerState` function returns, and there is no `params` key. 

![image](https://github.com/algolia/instantsearch/assets/101807528/0aaf1887-c4e5-41d8-9c85-19e81461664d)

**Comment by dhayab** [comment]
Hi, could you verify that `params` is removed from the response fields in your index configuration? This should be under Configuration > Search behavior > Retrieved attributes:

![image](https://github.com/algolia/instantsearch/assets/154633/465725f8-8193-46ae-a4b8-82cd71bd8627)

On our end we'll guard against this situation in an upcoming release of InstantSearch.

**Comment by volodymyr-strilets-mindcurv** [comment]
@dhayab you are right, we have a custom index config where the params field was not included. After adding it, now it works.
