### ISSUE TITLE
Samsung Note 20 Chrome has erratic behavior

### ISSUE THREAD

**Issue by DogByteMarketing** [algolia/instantsearch#5986]
### 🐛 Current behavior

When using Chrome on the Note 20 Ultra using the demo link provided in documentation it doesn't let you see results until you press enter. There's also an issue when pressing enter and changing the search query that it causes old results to display.

### 🔍 Steps to reproduce

Load chrome on a Note 20 (possibly other Samsung devices)
Pull up reproduction site
Start typing and you'll notice nothing displays
Hit enter and results appear
Delete results and type something else to see old results instead of new

### Live reproduction

https://codesandbox.io/p/sandbox/github/algolia/instantsearch/tree/master/examples/js/getting-started?file=%2Fsrc%2Fapp.js

### 💭 Expected behavior

The results to display properly as the data is typed how it performs in other mobile devices.

### Package version

4.63.0

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Haroenv** [comment]
I don't have access to a device to reproduce this right now, but I wonder if it possibly (although I don't really see how) could be related to https://github.com/algolia/instantsearch/pull/5963, do you mind trying out 4.62.0 and seeing if it still behaves wrongly?

**Comment by dhayab** [comment]
Hi, thanks for your feedback! It seems Samsung's keyboard "suggestion strip" feature acts as an IME. You can downgrade to 4.62.0 while we're working on a fix.

**Comment by tats-u** [comment]
I created a test page for testing keyboard events.

https://tats-u.github.io/kbdevents/

I recommend to use `compositionstart` to start caching the value in the most recent `changed` event until `compositionend`. If we receive `compositionend` and have a cached value, we can trigger a search by it.

**Comment by dhayab** [comment]
Hi, this issue has been fixed and it's available in the latest version of InstantSearch:

- instantsearch.js@4.64.2
- react-instantsearch@7.5.4
- vue-instantsearch@4.13.6
