### ISSUE TITLE
React native 0.73.2 ( expo 50 ), do not send any network requests

### ISSUE THREAD

**Issue by axelhildingson** [algolia/instantsearch#6025]
### 🐛 Current behavior

Hi 

I just update my app to Expo 50 from 49 and realised that didn't get any search results. I haven't seen any error logs or warnings from instant search. When I looked at the network traffic I could see that instantsearch.js queries was sent and we got results ( `client.multipleQueries([....])` ) but I couldn't se any request from react instantsearch. 

### 🔍 Steps to reproduce

Create a simple expo app 
```
<InstantSearch searchClient={....} indexName={...}>
  <SimpleComponentWithuseInfiniteHits />
</InstantSearch>
```
The result I get is hits: `[]`
and the _rawResults: `[{"exhaustiveFacetsCount": true, "exhaustiveNbHits": true, "hits": [], "hitsPerPage": 20, "index": "<indexname>", "nbHits": 0, "nbPages": 0, "page": 0, "params": "", "processingTimeMS": 0, "query": ""}]`

### Live reproduction

This is what I do, but we don't use react-native-web we render in an app [code sample](https://codesandbox.io/p/sandbox/jovial-napier-j3cg2c?file=%2Fsrc%2FApp.js)

### 💭 Expected behavior

Simple network request with hits.

### Package version

 "expo": "50.0.4", "react-native": "0.73.2", "react": "18.2.0", "algoliasearch": "^4.14.3", "react-instantsearch-core": "^7.3.0",`

### Operating system

IOS 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Haroenv** [comment]
Are the credentials correct? Could you make a reproducible example of this, it seems like it might not be related to react native itself, so maybe you can reproduce in regular React InstantSearch? We have a template available for that purpose [here](https://codesandbox.io/s/github/algolia/create-instantsearch-app/tree/templates/react-instantsearch). Thanks!

**Comment by axelhildingson** [comment]
This is what I do, but we don't use react-native-web we render in an app [code sample](https://codesandbox.io/p/sandbox/github/algolia/create-instantsearch-app/tree/templates/react-instantsearch?layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522cls1maudn00063b6h8lp2kxr5%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522cls1maudm00023b6hwawi5op9%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522cls1maudn00033b6hv6nlqlq8%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522cls1maudn00053b6hejahgp9h%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B62.22638634933128%252C37.77361365066872%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522cls1maudm00023b6hwawi5op9%2522%253A%257B%2522id%2522%253A%2522cls1maudm00023b6hwawi5op9%2522%252C%2522tabs%2522%253A%255B%255D%257D%252C%2522cls1maudn00053b6hejahgp9h%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522cls1maudn00043b6hgxjikstv%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A0%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522id%2522%253A%2522cls1maudn00053b6hejahgp9h%2522%252C%2522activeTabId%2522%253A%2522cls1maudn00043b6hgxjikstv%2522%257D%252C%2522cls1maudn00033b6hv6nlqlq8%2522%253A%257B%2522tabs%2522%253A%255B%255D%252C%2522id%2522%253A%2522cls1maudn00033b6hv6nlqlq8%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)

**Comment by axelhildingson** [comment]
I found the bug and it doesn't have anything to do with instant search ( create a fork and updated your expo example, I can create a PR for it if I have time ) 

The issue is  [react-native-gesture-handler](https://www.npmjs.com/package/react-native-gesture-handler), if you import it at the top of the project as react navigation recommend for stack navigation [stack navigation](https://reactnavigation.org/docs/stack-navigator/#installation) this bug will appear. I solved it by change from stack navigation to native stack navigation.

**Comment by axelhildingson** [comment]
I found the bug and it doesn't have anything to do with instant search ( create a fork and updated your expo example, I can create a PR for it if I have time )

The issue is [react-native-gesture-handler](https://www.npmjs.com/package/react-native-gesture-handler), if you import it at the top of the project as react navigation recommend for [stack navigation](https://reactnavigation.org/docs/stack-navigator/#installation) stack navigation this bug will appear. I solved it by change from stack navigation to native stack navigation.
