### ISSUE TITLE
`indexId` missing in `AutocompleteRenderState` type while being listed in the docs

### ISSUE THREAD

**Issue by axrez** [algolia/instantsearch#6049]
### 🐛 Current behavior

The [documentation for autocomplete](https://www.algolia.com/doc/api-reference/widgets/autocomplete/js/#connector-param-render-rendering-options) shows the `indices` containing a property named `indexId`, but this isn't reflected in the `AutocompleteRenderState` type [here](https://github.com/algolia/instantsearch/blob/master/packages/instantsearch.js/src/connectors/autocomplete/connectAutocomplete.ts#L38). This means that we can't index on the `indexId` without writing some smelly typescript.

### 🔍 Steps to reproduce

Providing steps to repro this type mismatch seems a bit excessive. However, I'm happy to do it if the above description isn't sufficient.

### Live reproduction

See comment above

### 💭 Expected behavior

I would expect the `AutocompleteRenderState` type in [this file](https://github.com/algolia/instantsearch/blob/master/packages/instantsearch.js/src/connectors/autocomplete/connectAutocomplete.ts#L38) to contain the `indexId` like described in the [docs](https://www.algolia.com/doc/api-reference/widgets/autocomplete/js/#connector-param-render-rendering-options).

### Package version

instantsearch.js 4.64.3

### Operating system

macOS 14.2.1

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Haroenv** [comment]
That's correct, thanks. I've just made a PR (https://github.com/algolia/instantsearch/pull/6050) to address this.

**Comment by axrez** [comment]
Wow that was fast. Thanks for moving so quickly on this 🙌
