### ISSUE TITLE
`useHits()` loose its page state in nextjs app router

### ISSUE THREAD

**Issue by duncanbla974** [algolia/instantsearch#6067]
### 🐛 Current behavior

If you navigate to a page > 0 then click on a product and want to go back to the listing page with the navigator back button, it looks like `useHits` loose the page state and show wrong products. While `uiState` page or `usePagination` currentRefinement are correct.

### 🔍 Steps to reproduce

1. Add a search query manually to the url (example: /search?instant_search%5Bquery%5D=le )
2. Navigate with the pagination to go on another page ( page 2, page 3, ...)
3. Click on a product
4. When in product page, click on the navigator back button

### Live reproduction

https://codesandbox.io/p/devbox/angry-rgb-7vdcfk

### 💭 Expected behavior

I expect the products on the listing page to be the same than before navigating to a product.

### Package version

nextjs 14.1.0, 

### Operating system

Windows

### Browser

Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by kirkwat** [comment]
how did you resolve this issue? I have a similar problem
