### ISSUE TITLE
bug: vue-instantsearch issues with vue 3.4

### ISSUE THREAD

**Issue by tkjaergaard** [algolia/instantsearch#6164]
### 🐛 Current behavior

When using the ais-configure component an error is thrown stating: "The `searchParameters` option expects an object. [...]".

The error is thrown in `instantsearch-js`:
https://github.com/algolia/instantsearch/blob/1b8e1d9680ca141861c715c030448b114b96f435/packages/instantsearch.js/src/connectors/configure/connectConfigure.ts#L84-L88

It's seems that the object that are passed along from 'ais-configure'  is a Proxy instance, and then the `isPlainObject` fails.

### 🔍 Steps to reproduce

![image](https://github.com/algolia/instantsearch/assets/1124666/74ec9269-b9e1-4cf7-920b-f3eaf68892ec)
![algolia-500](https://github.com/algolia/instantsearch/assets/1124666/d94ae8dc-ed20-45c9-a549-3cb796296ca0)

### Live reproduction

https://codesandbox.io/p/devbox/jovial-ioana-g5j43k?file=%2Fsrc%2FApp.vue%3A23%2C36

### 💭 Expected behavior

Should render without error.

### Package version

vue-instantsearch 4.16.0

### Operating system

MacOS 13.2.1

### Browser

Arc 1.37.0

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Haroenv** [comment]
Maybe here https://github.com/algolia/instantsearch/blob/master/packages/vue-instantsearch/src/components/Configure.js#L24 it should be `{...this.$attrs}` to solve that issue?

**Comment by LorenzoAsselinne** [comment]
We have the same issue, we'll try your fix locally. Thanks

**Comment by nickycdk** [comment]
Same issue here :(

**Comment by tkjaergaard** [comment]
@Haroenv Yep that solves the issue! 🎉

I can make a PR.
