### ISSUE TITLE
Headers are being used in client component

### ISSUE THREAD

**Issue by RobinGiel** [algolia/instantsearch#6232]
### 🐛 Current behavior

using version 0.3,1 that is an update here: [https://github.com/algolia/instantsearch/pull/6223/commits/bbb8c2a777a807da9ab7308f1f0c41c7ad4dae6e](here)

I see headers are being used in client component: https://nextjs.org/docs/app/api-reference/functions/headers

This causes issues when running locally:

![image](https://github.com/algolia/instantsearch/assets/13868698/94f21e15-7ce8-47ad-9a55-7ddfc9067f00)

more info about this issue why headers is out of context here: [link](https://nextjs.org/docs/messages/next-dynamic-api-wrong-context)

### 🔍 Steps to reproduce

running locally, when calling an actions or revalidating.

### Live reproduction

http://localhost:3000

### 💭 Expected behavior

No headers issue breaking dev 

### Package version

react-instantsearch-nextjs 0.3.1

### Operating system

Windows

### Browser

Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Hartoeft** [comment]
Have the same issue, with same package version.

**Comment by Haroenv** [comment]
This is fixed by https://github.com/algolia/instantsearch/pull/6228 and will be released in the next version today

**Comment by dhayab** [comment]
Hi, [react-instantsearch-nextjs@0.3.2](https://github.com/algolia/instantsearch/releases/tag/react-instantsearch-nextjs%400.3.2) is now available and should fix this issue.
