### ISSUE TITLE
Installation problem: Cannot find type definition file for 'googlemaps'

### ISSUE THREAD

**Issue by Annoxis** [algolia/instantsearch#6248]
### 🐛 Current behavior

Instantsearch.js/es/widgets/geo-search/geosearch.d.ts and Instantsearch.js/es/widgets/geo-search/createHTMLMarker.d.ts both have the following line of code: 
Line 2: `/// <reference types="googlemaps" />`
My IDE gives the following error regarding that line: "Cannot find type definition file for 'googlemaps'" and Angular will give me the same error during an ng serve.

If I attempt to install @types/googlemaps to solve the issue, every declaration it has in common with @types/google.maps get a Duplicate Identifier error. 

Removing the line fixes the issue as a workaround, but it won't be applicable in production. 
This line is also not in your source code, which I'll assume it is generated by something.

### 🔍 Steps to reproduce

Simply download the relevant libraries, start a basic angular project and attempt to launch the front end.
I am sorry, I have not been able to run the codesandbox online, but it worked locally.

### Live reproduction

https://codesandbox.io/p/github/Annoxis/instantsearch_googlemaps_import_problem/main?file=%2Fmy-angular-app%2Fpackage-lock.json&workspaceId=7fae891e-38f3-4e2e-9b6a-9d119ae163ab

### 💭 Expected behavior

My front end compile.

### Package version

Instantsearch.js 4.72.1, types/google.maps 3.55.9, angular 17.3.4, npm 10.5.0

### Operating system

Tested under Mac Sonoma and Windows 11 (WSL 2)

### Browser

Irrelevant

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

**Comment by Haroenv** [comment]
Interestingly this doesn't seem to be the case anymore with the latest build of `master` (which uses typescript 5.5.2). Therefore the next release (scheduled for tomorrow) won't have the automatic insertion of `///reference` and it should work all fine.

You can double check this by running this deploy preview: https://github.com/algolia/instantsearch/pull/6246#issuecomment-2182248652

I haven't seen any other reports about this in the past, but I do know that at some point the identifier changed from types/google.maps to types/googlemaps (or the other way round, not sure anymore now)

**Comment by Annoxis** [comment]
The 4.72.2 update effectively solved the issue, but now, another issue arose: "Cannot find namespace 'google'" in a dozen places in nodes_modules/instantsearch.js/es/widgets/geo-search/geo-search.d.ts and nodes_modules/instantsearch.js/es/widgets/geo-search/createHTMLMarker.d.ts. 

Also, in nodes_modules/instantsearch.js/es/widgets/geo-search/geo-search.d.ts, I get the following:

- LIne 121:36 : Property 'google' does not exist on type 'Window & typeof globalThis'
- Line 213:51 : Cannot find name 'google'

**Comment by Annoxis** [comment]
Actually, the issue I get now is different, so I am closing this issue. The new problem is described in this issue: [here](https://github.com/algolia/instantsearch/issues/6253)
