### ISSUE TITLE
Installation problem: Property 'MarkerOptions' does not exist on type 'typeof maps'' 

### ISSUE THREAD

**Issue by Annoxis** [algolia/instantsearch#6253]
### 🐛 Current behavior

I get the following error at instantsearch.js/es/widgets/geo-search/geo-search.d.ts:213:63 : Property 'MarkerOptions' does not exist on type 'typeof maps'.
Here is the faulty line of code: `markerOptions: GeoSearchMarker<typeof google.maps.MarkerOptions | Partial<HTMLMarkerArguments>>;`

Removing "typeof" fixes the issue as a workaround for development, but it won't be applicable in production.

### 🔍 Steps to reproduce

Simply download the relevant libraries, start a basic angular project and attempt to launch the front end.
I am sorry, I have not been able to run the codesandbox online, but it worked locally.

### Live reproduction

https://codesandbox.io/p/github/Annoxis/instantsearch_googlemaps_import_problem/main

### 💭 Expected behavior

My front end compile.

### Package version

Instantsearch.js 4.72.2, types/google.maps 3.55.10, angular 15.2, npm 10.5.0

### Operating system

Tested under Mac Sonoma and Windows 11 (WSL 2)

### Browser

Irrelevant

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Haroenv** [comment]
Your sandbox seems to be private, but I tried to reproduce and I don't see an error: https://codesandbox.io/p/sandbox/friendly-ben-jzt2xs?file=%2Fsearch.ts%3A100%2C1-111%2C6

**Comment by Annoxis** [comment]
@Haroenv I updated the codesandbox, it should work now. The main difference between our codes is that I am using Angular and you are not, which matters since the issue appears in a Typescript file.

**Comment by KennethHoff** [comment]
I can attest to this. It does not compile for me either.

**Comment by antoniobuyukluev** [comment]
Same on my end

**Comment by Haroenv** [comment]
I wonder if this is caused by somehow you having both `@types/googlemaps` and `@types/google.maps` installed. Can you check that? And if removing one of the two manually works

**Comment by antoniobuyukluev** [comment]
> I wonder if this is caused by somehow you having both `@types/googlemaps` and `@types/google.maps` installed. Can you check that? And if removing one of the two manually works

![image](https://github.com/user-attachments/assets/6eb4507e-413a-4c6b-97d0-9edea45d8b0c)
i have only one type

**Comment by antoniobuyukluev** [comment]
@Haroenv 
![image](https://github.com/user-attachments/assets/1bb2b576-8e0c-4e23-93a8-f84cb6193b9f)
i think this is the reason

**Comment by Haroenv** [comment]
Thanks, I believe the changes in https://github.com/algolia/instantsearch/pull/6319 will fix the issue then. Do you mind using the version that codesandbox will provide in the PR locally and see if that all works? thanks!
