### ISSUE TITLE
React-Instantsearch Typescript, hits is depreciated on 7.12.0

### ISSUE THREAD

**Issue by Kashi-Datum** [algolia/instantsearch#6272]
### 🐛 Current behavior

Currently, I am using the following code:

```
const { hits } = useInfiniteHits<MyType>();
```

This is giving me an error inside of VSCode stating that hits is depreciated.

Reverting to 7.11.0 resolves the issue, however I end up running into typing problems as seen and described in https://github.com/algolia/instantsearch/issues/5989

Doing some digging, it is asking me to use ```items``` instead of ```hits```, however this is not described in the InfiniteHits hook description seen here:

https://www.algolia.com/doc/api-reference/widgets/infinite-hits/react/

Can we the change of depreciating {hits} from useInfiniteHits() be removed from 7.12.0 until the documentation is properly updated?

### 🔍 Steps to reproduce

1. Install TypeScript
2. npm install algoliasearch react-instantsearch

Causes this issue in VSCode.

### Live reproduction

N/A

### 💭 Expected behavior

Either the keys for the hooks should match the documentation, or hits should be depreciated

### Package version

algoliasearch@latest, react-instantsearch@7.12.0

### Operating system

Windows 11

### Browser

Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Haroenv** [comment]
Ah that part of the docs was overlooked, sorry! I'll update it now

**Comment by Haroenv** [comment]
Updated in the docs now (will release soon). Thanks for pointing out this missed update
