### ISSUE TITLE
Circular dependency in `react-instantsearch-core`

### ISSUE THREAD

**Issue by andrewgaun** [algolia/instantsearch#6292]
### 🐛 Current behavior

Found a circular dependency in your dist code when rolling up a project. 
```
(!) Circular dependency
node_modules/react-instantsearch/node_modules/react-instantsearch-core/dist/es/index.js -> node_modules/react-instantsearch/node_modules/react-instantsearch-core/dist/es/server/index.js -> node_modules/react-instantsearch/node_modules/react-instantsearch-core/dist/es/server/getServerState.js -> node_modules/react-instantsearch/node_modules/react-instantsearch-core/dist/es/index.js
```

### 🔍 Steps to reproduce

1) `npm install react-instantsearch`
2) create a js file with `import  * from 'react-instantsearch'`
3) compile with rollup

### Live reproduction

N/A

### 💭 Expected behavior
The code would ideally not have a circular dependency.
I believe if the imports in [getServerState.js ](https://github.com/algolia/instantsearch/blob/master/packages/react-instantsearch-core/src/server/getServerState.tsx#L8-L13) were updated to point directly to the composites, this issue would be resolved.

```
import type { InstantSearchServerState, InstantSearchSSRProvider } from '../component/InstantSearchSSRProvider';
import type { InstantSearchServerContextApi, InstantSearchServerContext } from '../component/InstantSearchServerContext';
```
^ Not sure if this is valid but figure it is something along these lines :)

### Package version

react-instantsearch-core 7.12.2

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Haroenv** [comment]
Good catch, we didn't have code to prevent circles in those packages, only in InstantSearch.js apparently. I just fixed the circular dependency and ensured we can't accidentally add the loop later in https://github.com/algolia/instantsearch/pull/6294

**Comment by Haroenv** [comment]
This will be released when we next do a release, thanks
