### ISSUE TITLE
Send click events in vue 3 - TypeError: window.aa is not a function

### ISSUE THREAD

**Issue by jbp35** [algolia/instantsearch#6303]
### 🐛 Current behavior

I am trying to follow this guide to send click events in vue 3: 
https://www.algolia.com/doc/guides/building-search-ui/events/vue/

When calling `window.aa("setUserToken", "test-user-123")` to set user token, I get the error:

`TypeError: window.aa is not a function`

How to configure this using vue 3 ?

### 🔍 Steps to reproduce

- create a new vue project
- follow the steps in https://www.algolia.com/doc/guides/building-search-ui/events/vue/

### Live reproduction

h

### 💭 Expected behavior

User token should be set. 

### Package version

"vue-instantsearch": "^4.17.5", "vue": "^3.0.0",

### Operating system

windows

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Haroenv** [comment]
Have you added the insights client or `insights: true`?

**Comment by jbp35** [comment]
> Have you added the insights client or `insights: true`?

I am using insights: true

**Comment by Haroenv** [comment]
I wonder if maybe you're running the code before the insights library is loaded. If you always run the insights option on your website it can be a technique to load the library faster like this https://www.algolia.com/doc/api-client/methods/insights/?client=javascript#include-the-insights-client-in-your-html:

```html
<script>
  var ALGOLIA_INSIGHTS_SRC = "https://cdn.jsdelivr.net/npm/search-insights@2.15.0/dist/search-insights.min.js";

  !function(e,a,t,n,s,i,c){e.AlgoliaAnalyticsObject=s,e[s]=e[s]||function(){
  (e[s].queue=e[s].queue||[]).push(arguments)},e[s].version=(n.match(/@([^\/]+)\/?/) || [])[1],i=a.createElement(t),c=a.getElementsByTagName(t)[0],
  i.async=1,i.src=n,c.parentNode.insertBefore(i,c)
  }(window,document,"script",ALGOLIA_INSIGHTS_SRC,"aa");
</script>
```

**Comment by jbp35** [comment]
> I wonder if maybe you're running the code before the insights library is loaded. If you always run the insights option on your website it can be a technique to load the library faster like this https://www.algolia.com/doc/api-client/methods/insights/?client=javascript#include-the-insights-client-in-your-html:
> 
> ```
> <script>
>   var ALGOLIA_INSIGHTS_SRC = "https://cdn.jsdelivr.net/npm/search-insights@2.15.0/dist/search-insights.min.js";
> 
>   !function(e,a,t,n,s,i,c){e.AlgoliaAnalyticsObject=s,e[s]=e[s]||function(){
>   (e[s].queue=e[s].queue||[]).push(arguments)},e[s].version=(n.match(/@([^\/]+)\/?/) || [])[1],i=a.createElement(t),c=a.getElementsByTagName(t)[0],
>   i.async=1,i.src=n,c.parentNode.insertBefore(i,c)
>   }(window,document,"script",ALGOLIA_INSIGHTS_SRC,"aa");
> </script>
> ```

Thanks, I am not getting the error message anymore after adding this script in the index.html file of my vue app. Is it okay to use this in production?

However, I am not able to verify in Algolia dashboard / event debugger if the event are successfuly emitted. For some reason, the Debug events collected section of my app is stuck with the message: 

 `Failed to retrieve events from the Insights API. This could be due to a transient network error. Retrying in a few second`

Any idea how to fix this? Thank you!

**Comment by Haroenv** [comment]
Hi, yes you can use this in production, it's the official way to set up insights in advance.

For the network error I can't help you. If it's persistent you can contact support.

**Comment by jbp35** [comment]
> Hi, yes you can use this in production, it's the official way to set up insights in advance.
> 
> For the network error I can't help you. If it's persistent you can contact support.

OK, thank you! I figured what was causing the network in the mean time: I had to disable adbloquer when visiting the event debugger page on https://dashboard.algolia.com/
