### ISSUE TITLE
react-instantsearch import fails in jest jsdom environment since 7.11.0

### ISSUE THREAD

**Issue by chrisvltn** [algolia/instantsearch#6309]
### 🐛 Current behavior

After upgrading to `react-instantsearch@7.11.0`, our tests started to fail with the following error:

```
SyntaxError: Unexpected token 'export'
```

When investigating the issue, we found out it was introduced with [this change](https://github.com/algolia/instantsearch/compare/react-instantsearch-core@7.10.0...react-instantsearch-core@7.11.0#diff-ab6f88a95338456e6f91ca8aa8699155153f09b67f8b2aab1bca4708e47eb9bf), as now `../widgets` is imported instead of `../widgets/index/index`, and where [./answers/answers](https://github.com/algolia/instantsearch/blob/3707501a19e582e8263a3ae5a9d51ff3f5263361/packages/instantsearch.js/src/widgets/index.ts#L3) is imported, where [preact is imported](https://github.com/algolia/instantsearch/blob/3707501a19e582e8263a3ae5a9d51ff3f5263361/packages/instantsearch.js/src/widgets/answers/answers.tsx#L4).

Preact knows about this issue (https://github.com/preactjs/preact/issues/4406), but for now there is no plan on fixing it.

For now, I managed to get around this issue by adding a [testEnvironmentOptions.customExportConditions](https://jestjs.io/docs/configuration#testenvironmentoptions-object) jest configuration to our repository:

```js
testEnvironmentOptions: {
  customExportConditions: ['require'],
}
```

### 🔍 Steps to reproduce

1. Clone https://github.com/chrisvltn/algolia-jsdom-issue
2. Run `npm install`
3. Run `npm run test`

### Live reproduction

https://github.com/chrisvltn/algolia-jsdom-issue

### 💭 Expected behavior

Tests to pass without runtime error.

### Package version

react-instantsearch@7.11.0

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Haroenv** [comment]
Thanks, that change wasn't intentional, the import should have only been changed for the types. I'll revert the change in code and you'll be able to verify that works again in your setup.
