### ISSUE TITLE
Incorrect typing of ConfigureConnectorParams

### ISSUE THREAD

**Issue by Bcavez** [algolia/instantsearch#6329]
### 🐛 Current behavior

This might be a duplicate of https://github.com/algolia/instantsearch/issues/6297 or https://github.com/algolia/instantsearch/issues/5989

I have recently updated to the latest version:
"vue-instantsearch": "^4.19.2",
"algoliasearch": "^4.24.0",

And I am now getting a TS error for the ConfigureConnectorParams:
Object literal may only specify known properties, and 'filters' does not exist in type 'PlainSearchParameters'.
(Same issue for 'insideBoundingBox' and 'page')

I am using the connectStateResult connector and accessing the configure param this way:
 ```
instantsearchState.value.instantSearchInstance.renderState[indexName]?.configure?.refine({
  filters: ""
 })
```

I have tracked down the type of configure here: https://github.com/algolia/instantsearch/blob/62b6e4bbd27743cd0008548d7d59bd7cdb680b82/packages/instantsearch.js/src/connectors/configure/connectConfigure.ts#L22

It appears to be set to PlainSearchParameters whereas to me it should be SearchParameters no ? The code works and follows what is in the documentation, but the type does not reflect it.

### 🔍 Steps to reproduce

https://github.com/algolia/instantsearch/blob/62b6e4bbd27743cd0008548d7d59bd7cdb680b82/packages/instantsearch.js/src/connectors/configure/connectConfigure.ts#L22

### Live reproduction

//

### 💭 Expected behavior

Type should be SearchParameters instead of PlainSearchParameters ?

### Package version

"vue-instantsearch": "^4.19.2"

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Bcavez** [comment]
Related to this I am also getting an issue with algoliasearch-helper typing when using setQueryParameter()

Argument of type '"maxValuesPerFacet"' is not assignable to parameter of type 'keyof PlainSearchParameters'.

Yet according the documentation I should be able to use 'maxValuesPerFacet' and the code works.

The type definition is here https://github.com/algolia/instantsearch/blob/62b6e4bbd27743cd0008548d7d59bd7cdb680b82/packages/algoliasearch-helper/index.d.ts#L654

**Comment by Haroenv** [comment]
SearchParameters is the class, PlainSearchParameters is the interface, so the type is correct, but it seems somewhere (similar to the issues you mention) PlainSearchParameters (probably SearchOptions) becomes any/unknown. Do you have a reproduction somewhere on codesandbox or a repo that we can see and debug? Also ensure you're definitely on the latest version of specifically algoliasearch-helper, which is the relevant package here.

**Comment by Haroenv** [comment]
this is fixed in the latest version, thanks for noticing
