### ISSUE TITLE
Crawler will not read the sitemap URL

### ISSUE THREAD

**Issue by taylor-greene-ef** [algolia/instantsearch#6361]
### 🐛 Current behavior

*I could not find a repo for the crawler. Please direct me to that team as needed. 

When I run the crawler will not read the sitemap. 

### 🔍 Steps to reproduce

1. Create a crawler with `https://www.eftours.com/` as the starting point. 
2. Remove the startUrls param (we need the sitemap because it has more urls on it)
![image](https://github.com/user-attachments/assets/067a6734-496d-416c-bacf-089781a035b3)
3. Using the default setup run the crawler. It will not find any urls. 

### Live reproduction

NA

### 💭 Expected behavior

The sitemap should be read. 

I used [https://github.com/algolia/404-crawler](https://github.com/algolia/404-crawler) to see if the sitemap had an issue. No issues on the sitemap were found. It was able to read the file and find all the urls correctly. 

I also tried to contact support but haven't heard back in over a week [https://support.algolia.com/hc/en-us/requests/645792?page=1](https://support.algolia.com/hc/en-us/requests/645792?page=1)

### Package version

Algolia Crawler

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Haroenv** [comment]
you can go through https://support.algolia.com/hc/en-us for this. I'll close this issue as it's indeed not related to InstantSearch.
