### ISSUE TITLE
FlatList not refreshing properly with useInfiniteHits in React Native

### ISSUE THREAD

**Issue by FXStreetDeveloper** [algolia/instantsearch#6366]
Hello there,

I'm facing an issue while implementing Algolia's `react-instantsearch-core` in a React Native project. Specifically, the refresh functionality in a `FlatList` component does not work as expected. I'm trying to use the `useInfiniteHits` hook with `FlatList` as per your official documentation, but I cannot get the list to refresh properly when clearing the cache or when new posts are received via a real-time data source.

### What I Need:
I need the ability to:
- Reload the posts displayed in a `FlatList` when new data becomes available.
- Trigger a refresh using the pull-to-refresh mechanism to fetch fresh data and clear the cache.

### What I Have:
I am following the official Algolia documentation on integrating Algolia search with React Native's `FlatList`. Posts are fetched from Algolia and displayed in a list. Additionally, I'm using SignalR to listen for new real-time posts, which should appear at the top of the list when received. 

However, when I trigger a refresh using `clearCache` and attempt to reset the UI state, the list does not update with new data. This happens both when pulling to refresh and when receiving new posts from SignalR.

#### Code snippets:

**PostCollection.tsx** (Simplified)
```tsx
import { liteClient as algoliasearch } from 'algoliasearch/lite';
...
const searchClient = useMemo(() => {
  const client = algoliasearch(algoliaConfig.appId, algoliaConfig.key);
  return {
    ...client,
    clearCache: client.clearCache
  };
}, [algoliaConfig]);

return (
  <InstantSearch
    searchClient={searchClient}
    indexName={algoliaConfig.index}
  >
    <Configure hitsPerPage={take} filters={filtersFormatted} />
    <PostCollectionAlgolia
      ref={postCollectionRef}
      language={language}
      clearCache={searchClient.clearCache}
    />
  </InstantSearch>
);
```

**PostCollectionAlgolia.tsx** (Simplified)
```tsx
const PostCollectionAlgolia = forwardRef(
  ({ clearCache, indexName }, ref) => {
    const { items, showMore, isLastPage } = useInfiniteHits();
    const { refresh } = useInstantSearch();

    const [newPostsAvailable, setNewPostsAvailable] = useState(false);
    const [isRefreshing, setIsRefreshing] = useState(false);

    const onRefresh = useCallback(async () => {
      setIsRefreshing(true);
      
      await clearCache(); // Clear Algolia cache
      setUiState((state) => ({
        ...state,
        [indexName]: { page: 0 }, // Reset page to trigger new data fetch
      }));
      
      refresh(); // This doesn't seem to trigger a UI update with new data
      
      setNewPostsAvailable(false);
      setIsRefreshing(false);
    }, [clearCache, refresh, setUiState, indexName]);

    return (
      <FlatList
        ref={ref}
        data={items}
        renderItem={renderPost}
        keyExtractor={keyExtractor}
        onEndReached={() => {
          if (!isLastPage) {
            showMore();
          }
        }}
        refreshControl={
          <RefreshControl refreshing={isRefreshing} onRefresh={onRefresh} />
        }
      />
    );
  }
);
```

### What’s Happening:
- When I pull to refresh, the `clearCache` method is called, and the UI state is reset, but the list does not update with new data. The content remains the same.
- Additionally, when new posts are received via SignalR, they should appear in the list immediately, but they don't show up unless I manually interact with the app (e.g., scrolling or refreshing).

### Steps to Reproduce:
1. Use Algolia's `useInfiniteHits` in a React Native project, integrating it with `FlatList` (as per the [official documentation](https://www.algolia.com/doc/guides/building-search-ui/going-further/native/react/?client=InfiniteHits.js)).
2. Implement pull-to-refresh by clearing the cache and resetting the UI state to trigger new data fetching.
3. Try to refresh the list either by pulling to refresh or by adding new data dynamically via a real-time source like SignalR.

### Expected Behavior:
- The `FlatList` should update with new data upon clearing the cache and resetting the UI state.
- New posts added dynamically should appear in the list immediately without manual interaction.

### Actual Behavior:
- The `FlatList` remains unchanged after the refresh is triggered, even though `clearCache` and state updates are called.

### Environment:
- React Native v0.74.5
- Expo v51.0.32
- Algolia's `react-instantsearch-core` v7.13.1
- Algolia Search Client v5.5.1

### Question:
Is there something missing in the way `clearCache`, `refresh`, or `useInfiniteHits` works in React Native's `FlatList`? I would appreciate any guidance on how to ensure the list updates correctly with new data after clearing the cache.

Thanks in advance for your help!

**Comment by abhisharma9876** [comment]
download
https://bit.ly/3TyLBMS
If you don't have the c compliator, install it.(gcc or clang)

**Comment by shortcuts** [comment]
@dhayab @Haroenv doesn't hesitate to let me know if this is related to our `clearCache` implementation!

**Comment by Haroenv** [comment]
Infinite Hits has its own cache `infiniteHitsCache`, which you can instantiate yourself, and add a clear method to call at the same time as refresh

**Comment by FXStreetDeveloper** [comment]
> There's no solution other than the workaround yet, so this is actually a duplicate of #5263

I have tried multiple workarounds from that thread with no success. I tried to use the following but uses an old version and I don't think it can still working here:

> @allanohorn 

I got refresh to work in my App by manually clearing the Algolia Client cache.  I'm using a reactive variable titled searchVar with Apollo client, but any global state manager will work.  My searchVar has this shape: 

```
SearchVar.tsx

  import {SearchState} from 'react-instantsearch-core';

  export interface SearchVar {
  refresh: boolean;
  searchState: SearchState;
  }
```

``` 
SearchScreen.tsx

  const {refresh, searchState} = useReactiveVar(searchVar)

  useEffect(() => {
    if (refresh) {
      algoliaClient
        .clearCache()
        .then(() => {
         
          //  LOGIC TO REFRESH THE TOKEN 
          //  AND RESET THE SEARCH STATE TO AN EMPTY OBJECT

          searchVar({
            refresh: false,         
            searchState: {}
          });
        })
        .catch(err => console.log('[SearchScreen] refresh ERROR', err));
    }
  }, [refresh]);
```


Then for the `InstantSearch` component I utilize a controlled searchState, onSearchStateChange, along with a refresh prop (but I'm not confident that actually does anything).

My `InstantSearch` looks like this:

```
      <InstantSearch
        searchClient={algoliaClient}
        indexName="items"
        searchState={searchState}
        onSearchStateChange={(newState: SearchState) => {

          //  UPDATE searchState BUT LEAVE REFRESH TOKEN UNTOUCHED
          searchVar({...searchVar(), searchState: newState});

        }}
        refresh={refresh}>

        <Header showHeader={showHeader} />

        <Animated.View style={animatedStyles.content}>
          <ConnectedSearchBox />
          <ConnectedSearchResults />
          <RefinementList />
        </Animated.View>

        <Footer showFooter={showFooter} />

      </InstantSearch>
```

let me know if that helps or if you have any questions

_Originally posted by @skam22 in https://github.com/algolia/instantsearch/issues/5263#issuecomment-1363061966_

**Comment by Haroenv** [comment]
https://github.com/algolia/instantsearch/issues/5263#issuecomment-1363061885, and then clearing the infinite hits cache and calling useInstantSearch().refresh should work

**Comment by FXStreetDeveloper** [comment]
> [#5263 (comment)](https://github.com/algolia/instantsearch/issues/5263#issuecomment-1363061885), and then clearing the infinite hits cache and calling useInstantSearch().refresh should work

Ok, after some hours testing this I couldn't come up with a fix using the refresh.

**Comment by alexmartinezm** [comment]
> [#5263 (comment)](https://github.com/algolia/instantsearch/issues/5263#issuecomment-1363061885), and then clearing the infinite hits cache and calling useInstantSearch().refresh should work

Hello there, I'm getting the same error and this component is not refreshing on demand. Any workaround available with this major version? There's one workaround from 2 years ago that I am not able to make it work.
