### ISSUE TITLE
react-instantsearch-nextjs 0.3.13 issues

### ISSUE THREAD

**Issue by anthonybachour** [algolia/instantsearch#6393]
### 🐛 Current behavior

After updating package to 0.3.13 I am receiving a ton of errors in server logs.

Everything seems fine on the frontend except this is causing a 500 error when page is returned. (Page works fine but 500 code with html returned)

I tried removing my custom router but still having the same issue.

It seems to be related to the useConnector hook.

`TypeError: Cannot read properties of null (reading 'state')
    at VirtualSearchBox (./src/components/Search.tsx:1208:71)
digest: "1146631733"
 ⨯ TypeError: Cannot read properties of null (reading 'state')
    at VirtualClearRefinements (./src/components/Search.tsx:1212:78)
digest: "591784411"
 ⨯ TypeError: Cannot read properties of null (reading 'state')
    at VirtualRefinementList (./src/components/Search.tsx:1216:75)
digest: "2406044486"
 ⨯ TypeError: Cannot read properties of null (reading 'state')
    at VirtualRefinementList (./src/components/Search.tsx:1216:75)
digest: "2406044486"
 ⨯ TypeError: Cannot read properties of null (reading 'state')
    at VirtualSortBy (./src/components/Search.tsx:1220:68)
digest: "1775276621"
 ⨯ TypeError: Cannot read properties of null (reading 'state')
    at VirtualPagination (./src/components/Search.tsx:1224:72)
digest: "3596797007"
 ⨯ TypeError: Cannot read properties of null (reading 'state')
    at VirtualHierarchicalMenu (./src/components/Search.tsx:1228:78)
digest: "2688870463"
 ⨯ TypeError: Cannot read properties of null (reading 'state')
    at VirtualMenu (./src/components/Search.tsx:1232:66)
digest: "2879452850"
 ⨯ Internal error: TypeError: Cannot read properties of null (reading 'state')
    at eval (./node_modules/.pnpm/react-instantsearch-core@7.13.2_algoliasearch@5.7.0_react@18.3.1/node_modules/react-instantsearch-core/dist/es/hooks/useConnector.js:105:23)`

### 🔍 Steps to reproduce

Upgrade react-instantsearch-nextjs version 0.3.12 to 0.3.13

### Live reproduction

none

### 💭 Expected behavior

Should work as normal

### Package version

react-instantsearch-nextjs 0.3.13

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Haroenv** [comment]
hmm the only change in that version is https://github.com/algolia/instantsearch/pull/6372, not sure how it could be relevant. Do you have a sandbox or repository that shows this difference in behaviour?

**Comment by anthonybachour** [comment]
I tried running the app router example from the release codedeploy and it looks like it's not working (can't find qs module):

https://codesandbox.io/p/devbox/example-react-instantsearch-next-app-dir-example-j8jjdc

**Comment by anthonybachour** [comment]
@Haroenv here's an example where it fails: https://codesandbox.io/p/devbox/strange-cherry-1bvd7d

**Comment by anthonybachour** [comment]
@Haroenv here's an example where it fails: https://codesandbox.io/p/devbox/youthful-stonebraker-5c5xym

**Comment by jvalverdepa** [comment]
It seems like the error is gone when using `DynamicWidgets` component:


```
<InstantSearchNext
  routing
  indexName='queryIndex'
  searchClient={searchClient}
>
  <Configure ruleContexts={[]} />

  <DynamicWidgets>
    <Panel header='Brands'>
      <RefinementList
        attribute='brand'
        searchablePlaceholder='Search brands'
        searchable={true}
        showMore={true}
      />
    </Panel>
  </DynamicWidgets>

  <SearchBox />
  <Hits />
</InstantSearchNext>
```

**Comment by anthonybachour** [comment]
I played around with DynamicWidgets and actually something interesting happened.

When I wrap only the `Virtual` RefinementList, Menu etc the errors go away.

If I remove those same Virtual widgets instead of wrapping them the 500 errors appear again.

**Comment by aymeric-giraudet** [comment]
Hey, it's because of the `search.dispose()` I added sorry
Thought it would mitigate the memory leak further but it doesn't seem to change much.
Will push a fix next week, you can indeed use virtual dynamic widgets if this is blocking in the meantime
