### ISSUE TITLE
Documentation Wrong for Instant Scroll Demo

### ISSUE THREAD

**Issue by mmorris8** [algolia/instantsearch#6429]
### 🐛 Current behavior

https://www.algolia.com/doc/guides/building-search-ui/ui-and-ux-patterns/infinite-scroll/react/

hits is deprecated. The code flat out doesn't work if you copy it into a project. When was this last tested???

### 🔍 Steps to reproduce

Go to https://codesandbox.io/p/devbox/muddy-brook-nbdfm?file=%2Findex.html and try to build it. Doesn't work.

### Live reproduction

https://codesandbox.io/p/devbox/muddy-brook-nbdfm?file=%2Findex.html

### 💭 Expected behavior

The demo above, linked from the page, won't even build. Again, when was the last time this was tested???

### Package version

Irrelevant - Online Documentation is wrong.

### Operating system

OSX Sequoia

### Browser

Edge Latest

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Haroenv** [comment]
What do you mean it doesn't build? the example works for me perfectly fine. `hits` indeed should be changed to `items`, but for now both keys still work.

Build also seems to work:


<img width="424" alt="Screenshot 2024-11-12 at 10 08 57" src="https://github.com/user-attachments/assets/5481f0dd-89fe-4031-b427-73b12af31714">

**Comment by Haroenv** [comment]
I've made a pull request in the documentation to fix the `hits` that was still documented to use `items` like in the rest of the document
