### ISSUE TITLE
connectSortBy wipes it's sortBy setting when it is the default.

### ISSUE THREAD

**Issue by mmorris8** [algolia/instantsearch#6449]
### 🐛 Current behavior

connectSortBy is file node_modules/instantsearch.js/es/connectors/sort-by/connectSortBy.js

```javascript
getWidgetUiState: function getWidgetUiState(uiState, _ref4) {
        var searchParameters = _ref4.searchParameters;
        var currentIndex = searchParameters.index;
        return _objectSpread(_objectSpread({}, uiState), {}, {
          sortBy: currentIndex !== connectorState.initialIndex ? currentIndex : undefined
        });
      },
```

The code above doesn't make sense on the face of it. Why are we changing this to undefined when the currentIndex is the initial index? 

### 🔍 Steps to reproduce

See below. 

### Live reproduction

No sandbox should be necessary.

### 💭 Expected behavior

In my stateMapper's routetoState function, if I set an index sortBy to that index I should expect to sort on that index and not get a series of reloads and redirects, but the code above causes exactly this.  The correct code seems to be 

```javascript
return _objectSpread(_objectSpread({}, uiState), {}, {
          sortBy: currentIndex ?? connectorState.initialIndex
        });
```
This insures we have a value for sortBy if a sortBy value was provided.

If this isn't the case and the code is fine as is, then the documentation for building a custom stateMapper needs to be made far more clear as to what the initial value of the sortBy parameter should be when the default sort is to be used.

### Package version

instantsearch 4.75.4

### Operating system

OSX Sequoia

### Browser

Edge Latest

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Haroenv** [comment]
We ensure the default index doesn't show up in ui state, but instead gets applied in getWidgetSearchParameters so that the default index case doesn't need to be handled in routing (as most the default state of any widget doesn't show up in the url). If we'd have that in ui state, you'd either need to remove it in stateToRoute or have an update of the URL on first load of the page.

**Comment by Haroenv** [comment]
Which documentation do you mean? happy to update it with a suggestion that would be clearer for you!

**Comment by mmorris8** [comment]
This page: https://www.algolia.com/doc/guides/building-search-ui/going-further/routing-urls/js/

The section on rewritingURL's manually is the one that should make mention of it. I got the impression that I had to account for all aspects of the uiState.

And this isn't your team's fault - I just assumed. But documentation is a tricky thing.

Thank you for your time. After reading over this note please close.

**Comment by Haroenv** [comment]
I've added a note to that page, thanks. This issue will close once the PR in the documentation is merged automatically.
