### ISSUE TITLE
results.__isArtificial flag causes hydration error on Next.js App router

### ISSUE THREAD

**Issue by Stalex89** [algolia/instantsearch#6451]
### 🐛 Current behavior

The `__isArtificial` flag in `<NoResultsBoundary>` component (copied from the [documentation](https://www.algolia.com/doc/guides/building-search-ui/going-further/conditional-display/react/#display-a-message)
Shows UI hydration error on Next.js (App router).

When logging the `results` object from `useInstantSearch` by `console.log()` command, I've noticed the missing `__isArtificial` key on the client-side that may cause inconsistency between client-side and server-side rendering:

Server-side log:

```
SearchResults {
_rawResults: [
     {
       query: '',
       page: 0,
       hitsPerPage: 20,
       hits: [],
       nbHits: 0,
       nbPages: 0,
       params: '',
       exhaustiveNbHits: true,
       exhaustiveFacetsCount: true,
       processingTimeMS: 0,
       index: 'entries'
     }
   ],
   query: '',
   page: 0,
   hitsPerPage: 20,
   hits: [],
   nbHits: 0,
   nbPages: 0,
   params: '',
   exhaustiveNbHits: true,
   exhaustiveFacetsCount: true,
   processingTimeMS: 0,
   index: 'entries',
   persistHierarchicalRootCount: false,
   __isArtificial: true,
   disjunctiveFacets: [],
   hierarchicalFacets: [
     {
      name: 'entry_category',
      count: null,
      isRefined: true,
       path: null,
       escapedValue: null,
       exhaustive: true,
       data: null
     }
   ],
   facets: [],
   _state: SearchParameters {
     facets: [],
     disjunctiveFacets: [],
     hierarchicalFacets: [ [Object] ],
     facetsRefinements: {},
     facetsExcludes: {},
     disjunctiveFacetsRefinements: {},
     numericRefinements: {},
     tagRefinements: [],
     hierarchicalFacetsRefinements: { entry_category: [] },
     index: 'entries',
     query: '',
     maxValuesPerFacet: 10
   }
 }
```
Client-side log (see screenshot):

![Screenshot 2024-11-25 at 10 55 42](https://github.com/user-attachments/assets/8617175f-24ef-4e6c-b544-89b45f2daa13)

NoResultsBoundary component code:

```
"use client";

import React, { PropsWithChildren, ReactNode } from "react";
import { useInstantSearch } from "react-instantsearch";
import styles from "./SearchNoResultsBoundary.css";
import { useTranslations } from "next-intl";

type Props = PropsWithChildren & {
  fallback?: ReactNode;
};

const NoResults = () => {
  const { indexUiState } = useInstantSearch();
  const t = useTranslations();

  return (
    <div className={styles.base}>
      <p className={styles.message}>
        {t("search.no_results.message")} <q>{indexUiState.query}</q>.
      </p>
    </div>
  );
};

const SearchNoResultsBoundary = ({
  children,
  fallback = <NoResults />,
}: Props) => {
  const { results } = useInstantSearch();

  // The `__isArtificial` flag makes sure not to display the No Results message
  // when no hits have been returned.
  if (!results.__isArtificial && results.nbHits === 0) {
    return (
      <>
        {fallback}
        <div hidden>{children}</div>
      </>
    );
  }

  return children;
};

export default SearchNoResultsBoundary;

```

SearchProvider component:

```
"use client";

import { liteClient as algoliasearch } from "algoliasearch/lite";
import { ComponentProps, PropsWithChildren } from "react";
import { InstantSearchNext } from "react-instantsearch-nextjs";

type Props = PropsWithChildren &
  Omit<ComponentProps<typeof InstantSearchNext>, "searchClient">;

const ALGOLIA_APPLICATION_ID =
  process.env.NEXT_PUBLIC_ALGOLIA_APPLICATION_ID || "";
const ALGOLIA_SEARCH_API_KEY =
  process.env.NEXT_PUBLIC_ALGOLIA_SEARCH_API_KEY || "";

const algoliaClient =
  !!ALGOLIA_APPLICATION_ID && !!ALGOLIA_SEARCH_API_KEY
    ? algoliasearch(ALGOLIA_APPLICATION_ID, ALGOLIA_SEARCH_API_KEY)
    : null;

const searchClient = algoliaClient
  ? {
      ...algoliaClient,
      search(requests: any) {
        if (requests.every(({ params }: any) => !params.query)) {
          return Promise.resolve({
            results: requests.map(() => ({
              hits: [],
              nbHits: 0,
              nbPages: 0,
              page: 0,
              processingTimeMS: 0,
              hitsPerPage: 0,
              exhaustiveNbHits: false,
              query: "",
              params: "",
            })),
          });
        }
        return algoliaClient.search(requests);
      },
    }
  : null;

const SearchProvider = ({ children, ...rest }: Props) => {
  if (!searchClient) return children;
  return (
    <InstantSearchNext
      searchClient={searchClient}
      future={{
        preserveSharedStateOnUnmount: true,
      }}
      {...rest}
    >
      {children}
    </InstantSearchNext>
  );
};

export default SearchProvider;

```

**Updated**: I have noticed that the flag disappears when any other widget is added to the code, when only `<NoResultsBoundary>` is present in the code, the flag appears back.

### 🔍 Steps to reproduce

1. Install Next.js with app router
2. Use `react-instantsearch-next.js` package
3. Create `<NoResultsBoundary>` component according to the [documentation](https://www.algolia.com/doc/guides/building-search-ui/going-further/conditional-display/react/#display-a-message)
4. Wrap search results with `<NoResultsBoundary>` component

### Live reproduction

https://codesandbox.io/p/devbox/rough-sound-vpwpp3

### 💭 Expected behavior

`results.__isArtificial` flag is present in both server-side and client-side rendering and no UI hydration error 

### Package version

"next": "14.2.10", "algoliasearch": "^5.14.2", "react-instantsearch": "^7.13.8", "react-instantsearch-nextjs": "^0.3.18"

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by aymeric-giraudet** [comment]
Hey @Stalex89,

It's normal that we don't have `__isArtificial` as the package is made to render actual received results.

The problem is that `useInstantSearch` does not wait for the results, only `use*` (* being any widget) do, so that's why you receive `__isArtificial`.

I think you can skip that check. Probably `useInstantSearch` should wait for proper results, but in the meantime can you try to replace your SearchNoResultsBoundary with this (it's a bit hacky) : 
```tsx
const SearchNoResultsBoundary = ({
  children,
  fallback = <NoResults />,
}: Props) => {
  // This is just to wait for actual results as `useInstantSearch` does not
  useSearchbox();

  const { results } = useInstantSearch();

  if (!results.__isArtificial && results.nbHits === 0) {
    return (
      <>
        {fallback}
        <div hidden>{children}</div>
      </>
    );
  }

  return children;
};
```

We basically just added a `useSearchbox` call before without using the returned values, but it could be any other hook.
With this `__isArtificial` will always be `undefined` on the server, as it should. It should still work fine for CSR too. Tell me how it goes !

**Comment by Stalex89** [comment]
Hi @aymeric-giraudet, your suggestion fixes the UI error, thank you very much for you response!

I've doublechecked my code again, especially the part where I'm [detecting the empty query results and returning the formatted response](https://www.algolia.com/doc/guides/building-search-ui/going-further/conditional-requests/react/#detecting-empty-search-requests):

```
const searchClient = algoliaClient
  ? {
      ...algoliaClient,
      search(requests: any) {
        if (requests.every(({ params }: any) => !params.query)) {
          return Promise.resolve({
            results: requests.map(() => ({
              hits: [],
              nbHits: 0,
              nbPages: 0,
              page: 0,
              processingTimeMS: 0,
              hitsPerPage: 0,
              exhaustiveNbHits: false,
              query: "",
              params: "",
            })),
          });
        }
        return algoliaClient.search(requests);
      },
    }
  : null;
```
I've noticed that I'm not returning the `__isArtificial` flag here, so it's not present in the client and therefore causes the UI render to be different from server (thought it's not in the docs as well).

adding the `__isArtificial: true` to the response seems to fix my issue:

```
const searchClient = algoliaClient
  ? {
      ...algoliaClient,
      search(requests: any) {
        if (requests.every(({ params }: any) => !params.query)) {
          return Promise.resolve({
            results: requests.map(() => ({
              hits: [],
              ...
              __isArtificial: true,
            })),
          });
        }
        return algoliaClient.search(requests);
      },
    }
  : null;
```

Thank you again for your help! I will mark this issue as closed.
