### ISSUE TITLE
Multi-filter search on same index doesn't work for SSR

### ISSUE THREAD

**Issue by LuudJanssen** [algolia/instantsearch#6475]
### 🐛 Current behavior

Our site has product lister pages which are split up into sections. They search the same index, but show a subset of products with different filters. One section might show the title "Black T-Shirts" using filter `Color: Black` while the other might show "White T-Shirts" using filter `Color: White`.

Our set-up with `react-instantseach` looks something like this:

```tsx
<InstantSearch searchClient={searchClient}>
  <h2>Black T-Shirts</h2>
  <Index indexName="products">
    <Configure filters="Color:Black" hitsPerPage={8} />
    <Hits hitComponent={Hit} />
  </Index>

  <h2>White T-Shirts</h2>
  <Index indexName="products">
    <Configure filters="Color:White" hitsPerPage={8} />
    <Hits hitComponent={Hit} />
  </Index>
</InstantSearch>
```

And this works great. Except for when we introduce server-side rendering by using `getServerState()`. Example with Remix:

```tsx
export function loader() {
  return getServerState(<ProductLister />, { renderToString });
}

export default function ProductLister() {
  const serverState = useLoaderData<typeof loader>();

  return (
    <InstantSearchSSRProvider initialResults={serverState.initialResults}>
      {/* example from above */}
    </InstantSearchSSRProvider>
  );
}
```

When checking the server-side rendered HTML that gets produced, we noticed that both the "Black T-Shirts" section and the "White T-Shirts" section show the "White T-Shirts" results.

### 🔍 Steps to reproduce

1. Use `react-instantsearch` with two `<Index>` components targeting the same `indexName` but with different configuration.
2. Use `getServerState` w/ `<InstantSearchSSRProvider>` to enable server-side rendering.
3. View the server-rendered HTML.
4. Observe that the first index copies the result from the second index.

### Live reproduction

https://codesandbox.io/p/github/LuudJanssen/algolia-multi-index-server-side-rendering-bug-reproduction/main?import=true

> ⚠️ Be sure to view the HTML source of the sandbox preview. In the live preview, the client-side will refetch the query and update the results to what they should be. This only happens in the server-side rendered HTML result.

### 💭 Expected behavior

Each instance of `<Index>` has its own configuration, set of filters and results, just like with client-side rendering.

> While checking how `initialResults` is structured, I noticed the results are keyed by index name. This should probably be changed to a key that uses the index name, as well as any configuration like filters / facets / query, etc.

### Package version

7.13.9

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Haroenv** [comment]
If you want two indices with unrelated state, they need to have a different indexId to differentiate them. They can both have the same indexName, but the indexId needs to be unique, or else the same state will be used for both indices

**Comment by LuudJanssen** [comment]
This fixed it! Thanks so much for your help :)
