### ISSUE TITLE
Issue with ais-dynamic-widgets and ais-hierarchical-menu in Vue3

### ISSUE THREAD

**Issue by M1sterPl0w** [algolia/instantsearch#6487]
### 🐛 Current behavior

We are trying to use `ais-dynamic-widgets` in combination with `ais-hierarchical-menu` using the following versions:

- `algoliasearch`: `4.12.1`  
- `vue`: `3.2.25`  
- `vue-instantsearch`: `4.19.4`  

The `ais-hierarchical-menu` works perfectly on its own. However, when placed inside the `ais-dynamic-widgets`, nothing is rendered within the dynamic widget.  

Is this an expected behavior, or are we missing something in our configuration?  

![2024-12-20 13_26_36-instantsearch-app – Mozilla Firefox](https://github.com/user-attachments/assets/3c7bedc9-d90a-4f93-8a07-bbaa4024bf9b)

### 🔍 Steps to reproduce

The following code is in our `App.vue` 
Even with `facet="['*']"` gone it doesn't work.

```
<template>
  <div class="container">
    <ais-instant-search
      :search-client="searchClient"
      index-name="test"
      >
      <ais-dynamic-widgets :facet="['*']">
          <ais-hierarchical-menu :attributes="categories" />
      </ais-dynamic-widgets>
    </ais-instant-search>
  </div>
</template>

<script>
import algoliasearch from 'algoliasearch/lite';
import { AisDynamicWidgets, AisHierarchicalMenu  } from 'vue-instantsearch/vue3/es';

export default {
  components: {
    AisDynamicWidgets,
    AisHierarchicalMenu
  },
  data() {
    return {
      searchClient: algoliasearch(
        'secret',
        'secret'
      ),
      categories: ['categoryLevel0', 'categoryLevel1', 'categoryLevel2', 'categoryLevel3']
    };
  },
};
</script>
```

### Live reproduction

sandbox Vue doens't work?

### 💭 Expected behavior

The `ais-hierarchical-menu` should render properly inside the `ais-dynamic-widgets`, with minimal code. 

### Package version

algoliasearch 4.12.1,  vue 3.2.25, vue-instantsearch 4.19.4  

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Haroenv** [comment]
What is the setting in the facetOrdering?

**Comment by Haroenv** [comment]
Ah yes true, I forgot the setting is called facet display. Glad you have the solution!
